// Generated by rdgen - DO NOT EDIT MANUALLY
// Source: protocol/src/main/kotlin/model/rider/IndexMcpModel.kt
//
// These are the C# protocol stubs for the rd model. In a full build pipeline,
// rdgen generates these automatically from the protocol model definition.
// This compilation stub provides the same public API surface.
//
// At runtime in Rider, the real rdgen-generated code handles serialization and
// cross-process communication. These stubs just enable compilation.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using JetBrains.Lifetimes;

// ReSharper disable InconsistentNaming

namespace JetBrains.Rider.Model.IndexMcp
{
    // ── Common data structures ──────────────────────────────────────────────

    public sealed class RdSourcePosition
    {
        public string FilePath { get; }
        public int Line { get; }
        public int Column { get; }

        public RdSourcePosition(string filePath, int line, int column)
        {
            FilePath = filePath;
            Line = line;
            Column = column;
        }
    }

    public sealed class RdSymbolInfo
    {
        public string Name { get; }
        public string QualifiedName { get; }
        public string Kind { get; }
        public string? FilePath { get; }
        public int? Line { get; }
        public int? Column { get; }
        public string Language { get; }
        public string? Signature { get; }
        public List<string> Modifiers { get; }

        public RdSymbolInfo(
            string name,
            string qualifiedName,
            string kind,
            string? filePath,
            int? line,
            int? column,
            string language,
            string? signature,
            List<string> modifiers)
        {
            Name = name;
            QualifiedName = qualifiedName;
            Kind = kind;
            FilePath = filePath;
            Line = line;
            Column = column;
            Language = language;
            Signature = signature;
            Modifiers = modifiers;
        }
    }

    // ── Type Hierarchy ──────────────────────────────────────────────────────

    public sealed class RdTypeHierarchyRequest
    {
        public RdSourcePosition Position { get; }
        public string Scope { get; }

        public RdTypeHierarchyRequest(RdSourcePosition position, string scope)
        {
            Position = position;
            Scope = scope;
        }
    }

    public sealed class RdTypeHierarchyResult
    {
        public RdSymbolInfo Element { get; }
        public List<RdSymbolInfo> Supertypes { get; }
        public List<RdSymbolInfo> Subtypes { get; }

        public RdTypeHierarchyResult(RdSymbolInfo element, List<RdSymbolInfo> supertypes, List<RdSymbolInfo> subtypes)
        {
            Element = element;
            Supertypes = supertypes;
            Subtypes = subtypes;
        }
    }

    // ── Find Implementations ────────────────────────────────────────────────

    public sealed class RdImplementationsRequest
    {
        public RdSourcePosition Position { get; }
        public string Scope { get; }

        public RdImplementationsRequest(RdSourcePosition position, string scope)
        {
            Position = position;
            Scope = scope;
        }
    }

    public sealed class RdImplementationsResult
    {
        public List<RdSymbolInfo> Implementations { get; }

        public RdImplementationsResult(List<RdSymbolInfo> implementations)
        {
            Implementations = implementations;
        }
    }

    // ── Call Hierarchy ──────────────────────────────────────────────────────

    public sealed class RdCallHierarchyRequest
    {
        public RdSourcePosition Position { get; }
        public string Direction { get; }
        public int Depth { get; }
        public string Scope { get; }

        public RdCallHierarchyRequest(RdSourcePosition position, string direction, int depth, string scope)
        {
            Position = position;
            Direction = direction;
            Depth = depth;
            Scope = scope;
        }
    }

    public sealed class RdCallHierarchyResult
    {
        public RdSymbolInfo Root { get; }
        public List<RdSymbolInfo> Calls { get; }

        public RdCallHierarchyResult(RdSymbolInfo root, List<RdSymbolInfo> calls)
        {
            Root = root;
            Calls = calls;
        }
    }

    // ── Super Methods ───────────────────────────────────────────────────────

    public sealed class RdSuperMethodsRequest
    {
        public RdSourcePosition Position { get; }

        public RdSuperMethodsRequest(RdSourcePosition position)
        {
            Position = position;
        }
    }

    public sealed class RdSuperMethodInfo
    {
        public RdSymbolInfo Symbol { get; }
        public string ContainingTypeName { get; }
        public string ContainingTypeKind { get; }
        public bool IsInterface { get; }
        public int Depth { get; }

        public RdSuperMethodInfo(
            RdSymbolInfo symbol,
            string containingTypeName,
            string containingTypeKind,
            bool isInterface,
            int depth)
        {
            Symbol = symbol;
            ContainingTypeName = containingTypeName;
            ContainingTypeKind = containingTypeKind;
            IsInterface = isInterface;
            Depth = depth;
        }
    }

    public sealed class RdSuperMethodsResult
    {
        public RdSymbolInfo Method { get; }
        public List<RdSuperMethodInfo> Hierarchy { get; }

        public RdSuperMethodsResult(RdSymbolInfo method, List<RdSuperMethodInfo> hierarchy)
        {
            Method = method;
            Hierarchy = hierarchy;
        }
    }

    // ── File Structure ──────────────────────────────────────────────────────

    public sealed class RdFileStructureRequest
    {
        public string FilePath { get; }

        public RdFileStructureRequest(string filePath)
        {
            FilePath = filePath;
        }
    }

    public sealed class RdFlatStructureNode
    {
        public string Name { get; }
        public string Kind { get; }
        public string? Signature { get; }
        public List<string> Modifiers { get; }
        public int Line { get; }
        public int Depth { get; }

        public RdFlatStructureNode(string name, string kind, string? signature, List<string> modifiers, int line, int depth)
        {
            Name = name;
            Kind = kind;
            Signature = signature;
            Modifiers = modifiers;
            Line = line;
            Depth = depth;
        }
    }

    public sealed class RdFileStructureResult
    {
        public List<RdFlatStructureNode> Nodes { get; }

        public RdFileStructureResult(List<RdFlatStructureNode> nodes)
        {
            Nodes = nodes;
        }
    }

    // ── Rename Symbol ───────────────────────────────────────────────────────

    public sealed class RdRenameSymbolRequest
    {
        public RdSourcePosition Position { get; }
        public string NewName { get; }

        public RdRenameSymbolRequest(RdSourcePosition position, string newName)
        {
            Position = position;
            NewName = newName;
        }
    }

    public sealed class RdRenameSymbolResult
    {
        public bool Success { get; }
        public string OldName { get; }
        public string NewName { get; }
        public List<string> AffectedFiles { get; }
        public int ChangesCount { get; }
        public string Message { get; }

        public RdRenameSymbolResult(
            bool success,
            string oldName,
            string newName,
            List<string> affectedFiles,
            int changesCount,
            string message)
        {
            Success = success;
            OldName = oldName;
            NewName = newName;
            AffectedFiles = affectedFiles;
            ChangesCount = changesCount;
            Message = message;
        }
    }

    // ── RPC Call Abstraction ────────────────────────────────────────────────

    /// <summary>
    /// Simplified RPC call endpoint that mirrors <c>RdCall&lt;TReq, TRes&gt;</c> from the rd framework.
    /// In production, rdgen generates real RdCall instances with proper serialization.
    /// This stub just provides the SetAsync API that backend hosts use.
    /// </summary>
    public sealed class RdCallEndpoint<TReq, TRes>
    {
        private Func<Lifetime, TReq, Task<TRes>>? _handler;

        /// <summary>Register an async handler for this RPC call.</summary>
        public void SetAsync(Func<Lifetime, TReq, Task<TRes>> handler)
        {
            _handler = handler;
        }

        /// <summary>Invoke the registered handler (used for testing).</summary>
        public Task<TRes> InvokeAsync(Lifetime lifetime, TReq request)
        {
            if (_handler == null)
                throw new InvalidOperationException("No handler registered for this RPC call.");
            return _handler(lifetime, request);
        }
    }

    // ── Model ───────────────────────────────────────────────────────────────

    /// <summary>
    /// The rd protocol model for IDE Index MCP Server.
    /// In production, rdgen generates a class that extends RdExtReflectionBindableBase
    /// with proper serialization and protocol registration.
    /// This stub provides the same handler registration API.
    /// </summary>
    public class IndexMcpModel
    {
        public RdCallEndpoint<RdTypeHierarchyRequest, RdTypeHierarchyResult?> GetTypeHierarchy { get; }
        public RdCallEndpoint<RdImplementationsRequest, RdImplementationsResult?> FindImplementations { get; }
        public RdCallEndpoint<RdCallHierarchyRequest, RdCallHierarchyResult?> GetCallHierarchy { get; }
        public RdCallEndpoint<RdSuperMethodsRequest, RdSuperMethodsResult?> FindSuperMethods { get; }
        public RdCallEndpoint<RdFileStructureRequest, RdFileStructureResult?> GetFileStructure { get; }
        public RdCallEndpoint<RdRenameSymbolRequest, RdRenameSymbolResult?> RenameSymbol { get; }

        public IndexMcpModel()
        {
            GetTypeHierarchy = new RdCallEndpoint<RdTypeHierarchyRequest, RdTypeHierarchyResult?>();
            FindImplementations = new RdCallEndpoint<RdImplementationsRequest, RdImplementationsResult?>();
            GetCallHierarchy = new RdCallEndpoint<RdCallHierarchyRequest, RdCallHierarchyResult?>();
            FindSuperMethods = new RdCallEndpoint<RdSuperMethodsRequest, RdSuperMethodsResult?>();
            GetFileStructure = new RdCallEndpoint<RdFileStructureRequest, RdFileStructureResult?>();
            RenameSymbol = new RdCallEndpoint<RdRenameSymbolRequest, RdRenameSymbolResult?>();
        }
    }
}

