//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model.IndexMcp
{
  
  
  /// <summary>
  /// <p>Generated from: IndexMcpModel.kt:19</p>
  /// </summary>
  [JetBrains.Application.ShellComponent(Application.Parts.Instantiation.DemandAnyThreadSafe)]
  public class IndexMcpModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IRdEndpoint<RdTypeHierarchyRequest, RdTypeHierarchyResult> GetTypeHierarchy => _GetTypeHierarchy;
    [NotNull] public IRdEndpoint<RdImplementationsRequest, RdImplementationsResult> FindImplementations => _FindImplementations;
    [NotNull] public IRdEndpoint<RdCallHierarchyRequest, RdCallHierarchyResult> GetCallHierarchy => _GetCallHierarchy;
    [NotNull] public IRdEndpoint<RdSuperMethodsRequest, RdSuperMethodsResult> FindSuperMethods => _FindSuperMethods;
    [NotNull] public IRdEndpoint<RdFileStructureRequest, RdFileStructureResult> GetFileStructure => _GetFileStructure;
    [NotNull] public IRdEndpoint<RdRenameSymbolRequest, RdRenameSymbolResult> RenameSymbol => _RenameSymbol;
    
    //private fields
    [NotNull] private readonly RdCall<RdTypeHierarchyRequest, RdTypeHierarchyResult> _GetTypeHierarchy;
    [NotNull] private readonly RdCall<RdImplementationsRequest, RdImplementationsResult> _FindImplementations;
    [NotNull] private readonly RdCall<RdCallHierarchyRequest, RdCallHierarchyResult> _GetCallHierarchy;
    [NotNull] private readonly RdCall<RdSuperMethodsRequest, RdSuperMethodsResult> _FindSuperMethods;
    [NotNull] private readonly RdCall<RdFileStructureRequest, RdFileStructureResult> _GetFileStructure;
    [NotNull] private readonly RdCall<RdRenameSymbolRequest, RdRenameSymbolResult> _RenameSymbol;
    
    //primary constructor
    private IndexMcpModel(
      [NotNull] RdCall<RdTypeHierarchyRequest, RdTypeHierarchyResult> getTypeHierarchy,
      [NotNull] RdCall<RdImplementationsRequest, RdImplementationsResult> findImplementations,
      [NotNull] RdCall<RdCallHierarchyRequest, RdCallHierarchyResult> getCallHierarchy,
      [NotNull] RdCall<RdSuperMethodsRequest, RdSuperMethodsResult> findSuperMethods,
      [NotNull] RdCall<RdFileStructureRequest, RdFileStructureResult> getFileStructure,
      [NotNull] RdCall<RdRenameSymbolRequest, RdRenameSymbolResult> renameSymbol
    )
    {
      if (getTypeHierarchy == null) throw new ArgumentNullException("getTypeHierarchy");
      if (findImplementations == null) throw new ArgumentNullException("findImplementations");
      if (getCallHierarchy == null) throw new ArgumentNullException("getCallHierarchy");
      if (findSuperMethods == null) throw new ArgumentNullException("findSuperMethods");
      if (getFileStructure == null) throw new ArgumentNullException("getFileStructure");
      if (renameSymbol == null) throw new ArgumentNullException("renameSymbol");
      
      _GetTypeHierarchy = getTypeHierarchy;
      _FindImplementations = findImplementations;
      _GetCallHierarchy = getCallHierarchy;
      _FindSuperMethods = findSuperMethods;
      _GetFileStructure = getFileStructure;
      _RenameSymbol = renameSymbol;
      _GetTypeHierarchy.ValueCanBeNull = true;
      _FindImplementations.ValueCanBeNull = true;
      _GetCallHierarchy.ValueCanBeNull = true;
      _FindSuperMethods.ValueCanBeNull = true;
      _GetFileStructure.ValueCanBeNull = true;
      _RenameSymbol.ValueCanBeNull = true;
      BindableChildren.Add(new KeyValuePair<string, object>("getTypeHierarchy", _GetTypeHierarchy));
      BindableChildren.Add(new KeyValuePair<string, object>("findImplementations", _FindImplementations));
      BindableChildren.Add(new KeyValuePair<string, object>("getCallHierarchy", _GetCallHierarchy));
      BindableChildren.Add(new KeyValuePair<string, object>("findSuperMethods", _FindSuperMethods));
      BindableChildren.Add(new KeyValuePair<string, object>("getFileStructure", _GetFileStructure));
      BindableChildren.Add(new KeyValuePair<string, object>("renameSymbol", _RenameSymbol));
    }
    //secondary constructor
    private IndexMcpModel (
    ) : this (
      new RdCall<RdTypeHierarchyRequest, RdTypeHierarchyResult>(RdTypeHierarchyRequest.Read, RdTypeHierarchyRequest.Write, ReadRdTypeHierarchyResultNullable, WriteRdTypeHierarchyResultNullable),
      new RdCall<RdImplementationsRequest, RdImplementationsResult>(RdImplementationsRequest.Read, RdImplementationsRequest.Write, ReadRdImplementationsResultNullable, WriteRdImplementationsResultNullable),
      new RdCall<RdCallHierarchyRequest, RdCallHierarchyResult>(RdCallHierarchyRequest.Read, RdCallHierarchyRequest.Write, ReadRdCallHierarchyResultNullable, WriteRdCallHierarchyResultNullable),
      new RdCall<RdSuperMethodsRequest, RdSuperMethodsResult>(RdSuperMethodsRequest.Read, RdSuperMethodsRequest.Write, ReadRdSuperMethodsResultNullable, WriteRdSuperMethodsResultNullable),
      new RdCall<RdFileStructureRequest, RdFileStructureResult>(RdFileStructureRequest.Read, RdFileStructureRequest.Write, ReadRdFileStructureResultNullable, WriteRdFileStructureResultNullable),
      new RdCall<RdRenameSymbolRequest, RdRenameSymbolResult>(RdRenameSymbolRequest.Read, RdRenameSymbolRequest.Write, ReadRdRenameSymbolResultNullable, WriteRdRenameSymbolResultNullable)
    ) {}
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<RdTypeHierarchyResult> ReadRdTypeHierarchyResultNullable = RdTypeHierarchyResult.Read.NullableClass();
    public static CtxReadDelegate<RdImplementationsResult> ReadRdImplementationsResultNullable = RdImplementationsResult.Read.NullableClass();
    public static CtxReadDelegate<RdCallHierarchyResult> ReadRdCallHierarchyResultNullable = RdCallHierarchyResult.Read.NullableClass();
    public static CtxReadDelegate<RdSuperMethodsResult> ReadRdSuperMethodsResultNullable = RdSuperMethodsResult.Read.NullableClass();
    public static CtxReadDelegate<RdFileStructureResult> ReadRdFileStructureResultNullable = RdFileStructureResult.Read.NullableClass();
    public static CtxReadDelegate<RdRenameSymbolResult> ReadRdRenameSymbolResultNullable = RdRenameSymbolResult.Read.NullableClass();
    
    public static  CtxWriteDelegate<RdTypeHierarchyResult> WriteRdTypeHierarchyResultNullable = RdTypeHierarchyResult.Write.NullableClass();
    public static  CtxWriteDelegate<RdImplementationsResult> WriteRdImplementationsResultNullable = RdImplementationsResult.Write.NullableClass();
    public static  CtxWriteDelegate<RdCallHierarchyResult> WriteRdCallHierarchyResultNullable = RdCallHierarchyResult.Write.NullableClass();
    public static  CtxWriteDelegate<RdSuperMethodsResult> WriteRdSuperMethodsResultNullable = RdSuperMethodsResult.Write.NullableClass();
    public static  CtxWriteDelegate<RdFileStructureResult> WriteRdFileStructureResultNullable = RdFileStructureResult.Write.NullableClass();
    public static  CtxWriteDelegate<RdRenameSymbolResult> WriteRdRenameSymbolResultNullable = RdRenameSymbolResult.Write.NullableClass();
    
    protected override long SerializationHash => 1205334339629245198L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(JetBrains.Rider.Model.IdeRoot), JetBrains.Rider.Model.IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    public IndexMcpModel(Lifetime lifetime, IProtocol protocol) : this()
    {
      Identify(protocol.Identities, RdId.Root.Mix("IndexMcpModel"));
      this.BindTopLevel(lifetime, protocol, "IndexMcpModel");
    }
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("IndexMcpModel (");
      using (printer.IndentCookie()) {
        printer.Print("getTypeHierarchy = "); _GetTypeHierarchy.PrintEx(printer); printer.Println();
        printer.Print("findImplementations = "); _FindImplementations.PrintEx(printer); printer.Println();
        printer.Print("getCallHierarchy = "); _GetCallHierarchy.PrintEx(printer); printer.Println();
        printer.Print("findSuperMethods = "); _FindSuperMethods.PrintEx(printer); printer.Println();
        printer.Print("getFileStructure = "); _GetFileStructure.PrintEx(printer); printer.Println();
        printer.Print("renameSymbol = "); _RenameSymbol.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: IndexMcpModel.kt:72</p>
  /// </summary>
  public sealed class RdCallHierarchyRequest : IPrintable, IEquatable<RdCallHierarchyRequest>
  {
    //fields
    //public fields
    [NotNull] public RdSourcePosition Position {get; private set;}
    [NotNull] public string Direction {get; private set;}
    public int Depth {get; private set;}
    [NotNull] public string Scope {get; private set;}
    
    //private fields
    //primary constructor
    public RdCallHierarchyRequest(
      [NotNull] RdSourcePosition position,
      [NotNull] string direction,
      int depth,
      [NotNull] string scope
    )
    {
      if (position == null) throw new ArgumentNullException("position");
      if (direction == null) throw new ArgumentNullException("direction");
      if (scope == null) throw new ArgumentNullException("scope");
      
      Position = position;
      Direction = direction;
      Depth = depth;
      Scope = scope;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out RdSourcePosition position, [NotNull] out string direction, out int depth, [NotNull] out string scope)
    {
      position = Position;
      direction = Direction;
      depth = Depth;
      scope = Scope;
    }
    //statics
    
    public static CtxReadDelegate<RdCallHierarchyRequest> Read = (ctx, reader) => 
    {
      var position = RdSourcePosition.Read(ctx, reader);
      var direction = reader.ReadString();
      var depth = reader.ReadInt();
      var scope = reader.ReadString();
      var _result = new RdCallHierarchyRequest(position, direction, depth, scope);
      return _result;
    };
    
    public static CtxWriteDelegate<RdCallHierarchyRequest> Write = (ctx, writer, value) => 
    {
      RdSourcePosition.Write(ctx, writer, value.Position);
      writer.Write(value.Direction);
      writer.Write(value.Depth);
      writer.Write(value.Scope);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdCallHierarchyRequest) obj);
    }
    public bool Equals(RdCallHierarchyRequest other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Equals(Position, other.Position) && Direction == other.Direction && Depth == other.Depth && Scope == other.Scope;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Position.GetHashCode();
        hash = hash * 31 + Direction.GetHashCode();
        hash = hash * 31 + Depth.GetHashCode();
        hash = hash * 31 + Scope.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdCallHierarchyRequest (");
      using (printer.IndentCookie()) {
        printer.Print("position = "); Position.PrintEx(printer); printer.Println();
        printer.Print("direction = "); Direction.PrintEx(printer); printer.Println();
        printer.Print("depth = "); Depth.PrintEx(printer); printer.Println();
        printer.Print("scope = "); Scope.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: IndexMcpModel.kt:79</p>
  /// </summary>
  public sealed class RdCallHierarchyResult : IPrintable, IEquatable<RdCallHierarchyResult>
  {
    //fields
    //public fields
    [NotNull] public RdSymbolInfo Root {get; private set;}
    [NotNull] public List<RdSymbolInfo> Calls {get; private set;}
    
    //private fields
    //primary constructor
    public RdCallHierarchyResult(
      [NotNull] RdSymbolInfo root,
      [NotNull] List<RdSymbolInfo> calls
    )
    {
      if (root == null) throw new ArgumentNullException("root");
      if (calls == null) throw new ArgumentNullException("calls");
      
      Root = root;
      Calls = calls;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out RdSymbolInfo root, [NotNull] out List<RdSymbolInfo> calls)
    {
      root = Root;
      calls = Calls;
    }
    //statics
    
    public static CtxReadDelegate<RdCallHierarchyResult> Read = (ctx, reader) => 
    {
      var root = RdSymbolInfo.Read(ctx, reader);
      var calls = ReadRdSymbolInfoList(ctx, reader);
      var _result = new RdCallHierarchyResult(root, calls);
      return _result;
    };
    public static CtxReadDelegate<List<RdSymbolInfo>> ReadRdSymbolInfoList = RdSymbolInfo.Read.List();
    
    public static CtxWriteDelegate<RdCallHierarchyResult> Write = (ctx, writer, value) => 
    {
      RdSymbolInfo.Write(ctx, writer, value.Root);
      WriteRdSymbolInfoList(ctx, writer, value.Calls);
    };
    public static  CtxWriteDelegate<List<RdSymbolInfo>> WriteRdSymbolInfoList = RdSymbolInfo.Write.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdCallHierarchyResult) obj);
    }
    public bool Equals(RdCallHierarchyResult other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Equals(Root, other.Root) && Calls.SequenceEqual(other.Calls);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Root.GetHashCode();
        hash = hash * 31 + Calls.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdCallHierarchyResult (");
      using (printer.IndentCookie()) {
        printer.Print("root = "); Root.PrintEx(printer); printer.Println();
        printer.Print("calls = "); Calls.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: IndexMcpModel.kt:105</p>
  /// </summary>
  public sealed class RdFileStructureRequest : IPrintable, IEquatable<RdFileStructureRequest>
  {
    //fields
    //public fields
    [NotNull] public string FilePath {get; private set;}
    
    //private fields
    //primary constructor
    public RdFileStructureRequest(
      [NotNull] string filePath
    )
    {
      if (filePath == null) throw new ArgumentNullException("filePath");
      
      FilePath = filePath;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string filePath)
    {
      filePath = FilePath;
    }
    //statics
    
    public static CtxReadDelegate<RdFileStructureRequest> Read = (ctx, reader) => 
    {
      var filePath = reader.ReadString();
      var _result = new RdFileStructureRequest(filePath);
      return _result;
    };
    
    public static CtxWriteDelegate<RdFileStructureRequest> Write = (ctx, writer, value) => 
    {
      writer.Write(value.FilePath);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdFileStructureRequest) obj);
    }
    public bool Equals(RdFileStructureRequest other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return FilePath == other.FilePath;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + FilePath.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdFileStructureRequest (");
      using (printer.IndentCookie()) {
        printer.Print("filePath = "); FilePath.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: IndexMcpModel.kt:120</p>
  /// </summary>
  public sealed class RdFileStructureResult : IPrintable, IEquatable<RdFileStructureResult>
  {
    //fields
    //public fields
    [NotNull] public List<RdFlatStructureNode> Nodes {get; private set;}
    
    //private fields
    //primary constructor
    public RdFileStructureResult(
      [NotNull] List<RdFlatStructureNode> nodes
    )
    {
      if (nodes == null) throw new ArgumentNullException("nodes");
      
      Nodes = nodes;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out List<RdFlatStructureNode> nodes)
    {
      nodes = Nodes;
    }
    //statics
    
    public static CtxReadDelegate<RdFileStructureResult> Read = (ctx, reader) => 
    {
      var nodes = ReadRdFlatStructureNodeList(ctx, reader);
      var _result = new RdFileStructureResult(nodes);
      return _result;
    };
    public static CtxReadDelegate<List<RdFlatStructureNode>> ReadRdFlatStructureNodeList = RdFlatStructureNode.Read.List();
    
    public static CtxWriteDelegate<RdFileStructureResult> Write = (ctx, writer, value) => 
    {
      WriteRdFlatStructureNodeList(ctx, writer, value.Nodes);
    };
    public static  CtxWriteDelegate<List<RdFlatStructureNode>> WriteRdFlatStructureNodeList = RdFlatStructureNode.Write.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdFileStructureResult) obj);
    }
    public bool Equals(RdFileStructureResult other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Nodes.SequenceEqual(other.Nodes);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Nodes.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdFileStructureResult (");
      using (printer.IndentCookie()) {
        printer.Print("nodes = "); Nodes.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: IndexMcpModel.kt:111</p>
  /// </summary>
  public sealed class RdFlatStructureNode : IPrintable, IEquatable<RdFlatStructureNode>
  {
    //fields
    //public fields
    [NotNull] public string Name {get; private set;}
    [NotNull] public string Kind {get; private set;}
    [CanBeNull] public string Signature {get; private set;}
    [NotNull] public List<string> Modifiers {get; private set;}
    public int Line {get; private set;}
    public int Depth {get; private set;}
    
    //private fields
    //primary constructor
    public RdFlatStructureNode(
      [NotNull] string name,
      [NotNull] string kind,
      [CanBeNull] string signature,
      [NotNull] List<string> modifiers,
      int line,
      int depth
    )
    {
      if (name == null) throw new ArgumentNullException("name");
      if (kind == null) throw new ArgumentNullException("kind");
      if (modifiers == null) throw new ArgumentNullException("modifiers");
      
      Name = name;
      Kind = kind;
      Signature = signature;
      Modifiers = modifiers;
      Line = line;
      Depth = depth;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string name, [NotNull] out string kind, [CanBeNull] out string signature, [NotNull] out List<string> modifiers, out int line, out int depth)
    {
      name = Name;
      kind = Kind;
      signature = Signature;
      modifiers = Modifiers;
      line = Line;
      depth = Depth;
    }
    //statics
    
    public static CtxReadDelegate<RdFlatStructureNode> Read = (ctx, reader) => 
    {
      var name = reader.ReadString();
      var kind = reader.ReadString();
      var signature = ReadStringNullable(ctx, reader);
      var modifiers = ReadStringList(ctx, reader);
      var line = reader.ReadInt();
      var depth = reader.ReadInt();
      var _result = new RdFlatStructureNode(name, kind, signature, modifiers, line, depth);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    public static CtxReadDelegate<List<string>> ReadStringList = JetBrains.Rd.Impl.Serializers.ReadString.List();
    
    public static CtxWriteDelegate<RdFlatStructureNode> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Name);
      writer.Write(value.Kind);
      WriteStringNullable(ctx, writer, value.Signature);
      WriteStringList(ctx, writer, value.Modifiers);
      writer.Write(value.Line);
      writer.Write(value.Depth);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    public static  CtxWriteDelegate<List<string>> WriteStringList = JetBrains.Rd.Impl.Serializers.WriteString.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdFlatStructureNode) obj);
    }
    public bool Equals(RdFlatStructureNode other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Name == other.Name && Kind == other.Kind && Equals(Signature, other.Signature) && Modifiers.SequenceEqual(other.Modifiers) && Line == other.Line && Depth == other.Depth;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Name.GetHashCode();
        hash = hash * 31 + Kind.GetHashCode();
        hash = hash * 31 + (Signature != null ? Signature.GetHashCode() : 0);
        hash = hash * 31 + Modifiers.ContentHashCode();
        hash = hash * 31 + Line.GetHashCode();
        hash = hash * 31 + Depth.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdFlatStructureNode (");
      using (printer.IndentCookie()) {
        printer.Print("name = "); Name.PrintEx(printer); printer.Println();
        printer.Print("kind = "); Kind.PrintEx(printer); printer.Println();
        printer.Print("signature = "); Signature.PrintEx(printer); printer.Println();
        printer.Print("modifiers = "); Modifiers.PrintEx(printer); printer.Println();
        printer.Print("line = "); Line.PrintEx(printer); printer.Println();
        printer.Print("depth = "); Depth.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: IndexMcpModel.kt:61</p>
  /// </summary>
  public sealed class RdImplementationsRequest : IPrintable, IEquatable<RdImplementationsRequest>
  {
    //fields
    //public fields
    [NotNull] public RdSourcePosition Position {get; private set;}
    [NotNull] public string Scope {get; private set;}
    
    //private fields
    //primary constructor
    public RdImplementationsRequest(
      [NotNull] RdSourcePosition position,
      [NotNull] string scope
    )
    {
      if (position == null) throw new ArgumentNullException("position");
      if (scope == null) throw new ArgumentNullException("scope");
      
      Position = position;
      Scope = scope;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out RdSourcePosition position, [NotNull] out string scope)
    {
      position = Position;
      scope = Scope;
    }
    //statics
    
    public static CtxReadDelegate<RdImplementationsRequest> Read = (ctx, reader) => 
    {
      var position = RdSourcePosition.Read(ctx, reader);
      var scope = reader.ReadString();
      var _result = new RdImplementationsRequest(position, scope);
      return _result;
    };
    
    public static CtxWriteDelegate<RdImplementationsRequest> Write = (ctx, writer, value) => 
    {
      RdSourcePosition.Write(ctx, writer, value.Position);
      writer.Write(value.Scope);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdImplementationsRequest) obj);
    }
    public bool Equals(RdImplementationsRequest other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Equals(Position, other.Position) && Scope == other.Scope;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Position.GetHashCode();
        hash = hash * 31 + Scope.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdImplementationsRequest (");
      using (printer.IndentCookie()) {
        printer.Print("position = "); Position.PrintEx(printer); printer.Println();
        printer.Print("scope = "); Scope.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: IndexMcpModel.kt:66</p>
  /// </summary>
  public sealed class RdImplementationsResult : IPrintable, IEquatable<RdImplementationsResult>
  {
    //fields
    //public fields
    [NotNull] public List<RdSymbolInfo> Implementations {get; private set;}
    
    //private fields
    //primary constructor
    public RdImplementationsResult(
      [NotNull] List<RdSymbolInfo> implementations
    )
    {
      if (implementations == null) throw new ArgumentNullException("implementations");
      
      Implementations = implementations;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out List<RdSymbolInfo> implementations)
    {
      implementations = Implementations;
    }
    //statics
    
    public static CtxReadDelegate<RdImplementationsResult> Read = (ctx, reader) => 
    {
      var implementations = ReadRdSymbolInfoList(ctx, reader);
      var _result = new RdImplementationsResult(implementations);
      return _result;
    };
    public static CtxReadDelegate<List<RdSymbolInfo>> ReadRdSymbolInfoList = RdSymbolInfo.Read.List();
    
    public static CtxWriteDelegate<RdImplementationsResult> Write = (ctx, writer, value) => 
    {
      WriteRdSymbolInfoList(ctx, writer, value.Implementations);
    };
    public static  CtxWriteDelegate<List<RdSymbolInfo>> WriteRdSymbolInfoList = RdSymbolInfo.Write.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdImplementationsResult) obj);
    }
    public bool Equals(RdImplementationsResult other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Implementations.SequenceEqual(other.Implementations);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Implementations.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdImplementationsResult (");
      using (printer.IndentCookie()) {
        printer.Print("implementations = "); Implementations.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: IndexMcpModel.kt:126</p>
  /// </summary>
  public sealed class RdRenameSymbolRequest : IPrintable, IEquatable<RdRenameSymbolRequest>
  {
    //fields
    //public fields
    [NotNull] public RdSourcePosition Position {get; private set;}
    [NotNull] public string NewName {get; private set;}
    
    //private fields
    //primary constructor
    public RdRenameSymbolRequest(
      [NotNull] RdSourcePosition position,
      [NotNull] string newName
    )
    {
      if (position == null) throw new ArgumentNullException("position");
      if (newName == null) throw new ArgumentNullException("newName");
      
      Position = position;
      NewName = newName;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out RdSourcePosition position, [NotNull] out string newName)
    {
      position = Position;
      newName = NewName;
    }
    //statics
    
    public static CtxReadDelegate<RdRenameSymbolRequest> Read = (ctx, reader) => 
    {
      var position = RdSourcePosition.Read(ctx, reader);
      var newName = reader.ReadString();
      var _result = new RdRenameSymbolRequest(position, newName);
      return _result;
    };
    
    public static CtxWriteDelegate<RdRenameSymbolRequest> Write = (ctx, writer, value) => 
    {
      RdSourcePosition.Write(ctx, writer, value.Position);
      writer.Write(value.NewName);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdRenameSymbolRequest) obj);
    }
    public bool Equals(RdRenameSymbolRequest other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Equals(Position, other.Position) && NewName == other.NewName;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Position.GetHashCode();
        hash = hash * 31 + NewName.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdRenameSymbolRequest (");
      using (printer.IndentCookie()) {
        printer.Print("position = "); Position.PrintEx(printer); printer.Println();
        printer.Print("newName = "); NewName.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: IndexMcpModel.kt:131</p>
  /// </summary>
  public sealed class RdRenameSymbolResult : IPrintable, IEquatable<RdRenameSymbolResult>
  {
    //fields
    //public fields
    public bool Success {get; private set;}
    [NotNull] public string OldName {get; private set;}
    [NotNull] public string NewName {get; private set;}
    [NotNull] public List<string> AffectedFiles {get; private set;}
    public int ChangesCount {get; private set;}
    [NotNull] public string Message {get; private set;}
    
    //private fields
    //primary constructor
    public RdRenameSymbolResult(
      bool success,
      [NotNull] string oldName,
      [NotNull] string newName,
      [NotNull] List<string> affectedFiles,
      int changesCount,
      [NotNull] string message
    )
    {
      if (oldName == null) throw new ArgumentNullException("oldName");
      if (newName == null) throw new ArgumentNullException("newName");
      if (affectedFiles == null) throw new ArgumentNullException("affectedFiles");
      if (message == null) throw new ArgumentNullException("message");
      
      Success = success;
      OldName = oldName;
      NewName = newName;
      AffectedFiles = affectedFiles;
      ChangesCount = changesCount;
      Message = message;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out bool success, [NotNull] out string oldName, [NotNull] out string newName, [NotNull] out List<string> affectedFiles, out int changesCount, [NotNull] out string message)
    {
      success = Success;
      oldName = OldName;
      newName = NewName;
      affectedFiles = AffectedFiles;
      changesCount = ChangesCount;
      message = Message;
    }
    //statics
    
    public static CtxReadDelegate<RdRenameSymbolResult> Read = (ctx, reader) => 
    {
      var success = reader.ReadBool();
      var oldName = reader.ReadString();
      var newName = reader.ReadString();
      var affectedFiles = ReadStringList(ctx, reader);
      var changesCount = reader.ReadInt();
      var message = reader.ReadString();
      var _result = new RdRenameSymbolResult(success, oldName, newName, affectedFiles, changesCount, message);
      return _result;
    };
    public static CtxReadDelegate<List<string>> ReadStringList = JetBrains.Rd.Impl.Serializers.ReadString.List();
    
    public static CtxWriteDelegate<RdRenameSymbolResult> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Success);
      writer.Write(value.OldName);
      writer.Write(value.NewName);
      WriteStringList(ctx, writer, value.AffectedFiles);
      writer.Write(value.ChangesCount);
      writer.Write(value.Message);
    };
    public static  CtxWriteDelegate<List<string>> WriteStringList = JetBrains.Rd.Impl.Serializers.WriteString.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdRenameSymbolResult) obj);
    }
    public bool Equals(RdRenameSymbolResult other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Success == other.Success && OldName == other.OldName && NewName == other.NewName && AffectedFiles.SequenceEqual(other.AffectedFiles) && ChangesCount == other.ChangesCount && Message == other.Message;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Success.GetHashCode();
        hash = hash * 31 + OldName.GetHashCode();
        hash = hash * 31 + NewName.GetHashCode();
        hash = hash * 31 + AffectedFiles.ContentHashCode();
        hash = hash * 31 + ChangesCount.GetHashCode();
        hash = hash * 31 + Message.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdRenameSymbolResult (");
      using (printer.IndentCookie()) {
        printer.Print("success = "); Success.PrintEx(printer); printer.Println();
        printer.Print("oldName = "); OldName.PrintEx(printer); printer.Println();
        printer.Print("newName = "); NewName.PrintEx(printer); printer.Println();
        printer.Print("affectedFiles = "); AffectedFiles.PrintEx(printer); printer.Println();
        printer.Print("changesCount = "); ChangesCount.PrintEx(printer); printer.Println();
        printer.Print("message = "); Message.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: IndexMcpModel.kt:28</p>
  /// </summary>
  public sealed class RdSourcePosition : IPrintable, IEquatable<RdSourcePosition>
  {
    //fields
    //public fields
    [NotNull] public string FilePath {get; private set;}
    public int Line {get; private set;}
    public int Column {get; private set;}
    
    //private fields
    //primary constructor
    public RdSourcePosition(
      [NotNull] string filePath,
      int line,
      int column
    )
    {
      if (filePath == null) throw new ArgumentNullException("filePath");
      
      FilePath = filePath;
      Line = line;
      Column = column;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string filePath, out int line, out int column)
    {
      filePath = FilePath;
      line = Line;
      column = Column;
    }
    //statics
    
    public static CtxReadDelegate<RdSourcePosition> Read = (ctx, reader) => 
    {
      var filePath = reader.ReadString();
      var line = reader.ReadInt();
      var column = reader.ReadInt();
      var _result = new RdSourcePosition(filePath, line, column);
      return _result;
    };
    
    public static CtxWriteDelegate<RdSourcePosition> Write = (ctx, writer, value) => 
    {
      writer.Write(value.FilePath);
      writer.Write(value.Line);
      writer.Write(value.Column);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdSourcePosition) obj);
    }
    public bool Equals(RdSourcePosition other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return FilePath == other.FilePath && Line == other.Line && Column == other.Column;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + FilePath.GetHashCode();
        hash = hash * 31 + Line.GetHashCode();
        hash = hash * 31 + Column.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdSourcePosition (");
      using (printer.IndentCookie()) {
        printer.Print("filePath = "); FilePath.PrintEx(printer); printer.Println();
        printer.Print("line = "); Line.PrintEx(printer); printer.Println();
        printer.Print("column = "); Column.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: IndexMcpModel.kt:90</p>
  /// </summary>
  public sealed class RdSuperMethodInfo : IPrintable, IEquatable<RdSuperMethodInfo>
  {
    //fields
    //public fields
    [NotNull] public RdSymbolInfo Symbol {get; private set;}
    [NotNull] public string ContainingTypeName {get; private set;}
    [NotNull] public string ContainingTypeKind {get; private set;}
    public bool IsInterface {get; private set;}
    public int Depth {get; private set;}
    
    //private fields
    //primary constructor
    public RdSuperMethodInfo(
      [NotNull] RdSymbolInfo symbol,
      [NotNull] string containingTypeName,
      [NotNull] string containingTypeKind,
      bool isInterface,
      int depth
    )
    {
      if (symbol == null) throw new ArgumentNullException("symbol");
      if (containingTypeName == null) throw new ArgumentNullException("containingTypeName");
      if (containingTypeKind == null) throw new ArgumentNullException("containingTypeKind");
      
      Symbol = symbol;
      ContainingTypeName = containingTypeName;
      ContainingTypeKind = containingTypeKind;
      IsInterface = isInterface;
      Depth = depth;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out RdSymbolInfo symbol, [NotNull] out string containingTypeName, [NotNull] out string containingTypeKind, out bool isInterface, out int depth)
    {
      symbol = Symbol;
      containingTypeName = ContainingTypeName;
      containingTypeKind = ContainingTypeKind;
      isInterface = IsInterface;
      depth = Depth;
    }
    //statics
    
    public static CtxReadDelegate<RdSuperMethodInfo> Read = (ctx, reader) => 
    {
      var symbol = RdSymbolInfo.Read(ctx, reader);
      var containingTypeName = reader.ReadString();
      var containingTypeKind = reader.ReadString();
      var isInterface = reader.ReadBool();
      var depth = reader.ReadInt();
      var _result = new RdSuperMethodInfo(symbol, containingTypeName, containingTypeKind, isInterface, depth);
      return _result;
    };
    
    public static CtxWriteDelegate<RdSuperMethodInfo> Write = (ctx, writer, value) => 
    {
      RdSymbolInfo.Write(ctx, writer, value.Symbol);
      writer.Write(value.ContainingTypeName);
      writer.Write(value.ContainingTypeKind);
      writer.Write(value.IsInterface);
      writer.Write(value.Depth);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdSuperMethodInfo) obj);
    }
    public bool Equals(RdSuperMethodInfo other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Equals(Symbol, other.Symbol) && ContainingTypeName == other.ContainingTypeName && ContainingTypeKind == other.ContainingTypeKind && IsInterface == other.IsInterface && Depth == other.Depth;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Symbol.GetHashCode();
        hash = hash * 31 + ContainingTypeName.GetHashCode();
        hash = hash * 31 + ContainingTypeKind.GetHashCode();
        hash = hash * 31 + IsInterface.GetHashCode();
        hash = hash * 31 + Depth.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdSuperMethodInfo (");
      using (printer.IndentCookie()) {
        printer.Print("symbol = "); Symbol.PrintEx(printer); printer.Println();
        printer.Print("containingTypeName = "); ContainingTypeName.PrintEx(printer); printer.Println();
        printer.Print("containingTypeKind = "); ContainingTypeKind.PrintEx(printer); printer.Println();
        printer.Print("isInterface = "); IsInterface.PrintEx(printer); printer.Println();
        printer.Print("depth = "); Depth.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: IndexMcpModel.kt:86</p>
  /// </summary>
  public sealed class RdSuperMethodsRequest : IPrintable, IEquatable<RdSuperMethodsRequest>
  {
    //fields
    //public fields
    [NotNull] public RdSourcePosition Position {get; private set;}
    
    //private fields
    //primary constructor
    public RdSuperMethodsRequest(
      [NotNull] RdSourcePosition position
    )
    {
      if (position == null) throw new ArgumentNullException("position");
      
      Position = position;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out RdSourcePosition position)
    {
      position = Position;
    }
    //statics
    
    public static CtxReadDelegate<RdSuperMethodsRequest> Read = (ctx, reader) => 
    {
      var position = RdSourcePosition.Read(ctx, reader);
      var _result = new RdSuperMethodsRequest(position);
      return _result;
    };
    
    public static CtxWriteDelegate<RdSuperMethodsRequest> Write = (ctx, writer, value) => 
    {
      RdSourcePosition.Write(ctx, writer, value.Position);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdSuperMethodsRequest) obj);
    }
    public bool Equals(RdSuperMethodsRequest other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Equals(Position, other.Position);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Position.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdSuperMethodsRequest (");
      using (printer.IndentCookie()) {
        printer.Print("position = "); Position.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: IndexMcpModel.kt:98</p>
  /// </summary>
  public sealed class RdSuperMethodsResult : IPrintable, IEquatable<RdSuperMethodsResult>
  {
    //fields
    //public fields
    [NotNull] public RdSymbolInfo Method {get; private set;}
    [NotNull] public List<RdSuperMethodInfo> Hierarchy {get; private set;}
    
    //private fields
    //primary constructor
    public RdSuperMethodsResult(
      [NotNull] RdSymbolInfo method,
      [NotNull] List<RdSuperMethodInfo> hierarchy
    )
    {
      if (method == null) throw new ArgumentNullException("method");
      if (hierarchy == null) throw new ArgumentNullException("hierarchy");
      
      Method = method;
      Hierarchy = hierarchy;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out RdSymbolInfo method, [NotNull] out List<RdSuperMethodInfo> hierarchy)
    {
      method = Method;
      hierarchy = Hierarchy;
    }
    //statics
    
    public static CtxReadDelegate<RdSuperMethodsResult> Read = (ctx, reader) => 
    {
      var method = RdSymbolInfo.Read(ctx, reader);
      var hierarchy = ReadRdSuperMethodInfoList(ctx, reader);
      var _result = new RdSuperMethodsResult(method, hierarchy);
      return _result;
    };
    public static CtxReadDelegate<List<RdSuperMethodInfo>> ReadRdSuperMethodInfoList = RdSuperMethodInfo.Read.List();
    
    public static CtxWriteDelegate<RdSuperMethodsResult> Write = (ctx, writer, value) => 
    {
      RdSymbolInfo.Write(ctx, writer, value.Method);
      WriteRdSuperMethodInfoList(ctx, writer, value.Hierarchy);
    };
    public static  CtxWriteDelegate<List<RdSuperMethodInfo>> WriteRdSuperMethodInfoList = RdSuperMethodInfo.Write.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdSuperMethodsResult) obj);
    }
    public bool Equals(RdSuperMethodsResult other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Equals(Method, other.Method) && Hierarchy.SequenceEqual(other.Hierarchy);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Method.GetHashCode();
        hash = hash * 31 + Hierarchy.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdSuperMethodsResult (");
      using (printer.IndentCookie()) {
        printer.Print("method = "); Method.PrintEx(printer); printer.Println();
        printer.Print("hierarchy = "); Hierarchy.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: IndexMcpModel.kt:34</p>
  /// </summary>
  public sealed class RdSymbolInfo : IPrintable, IEquatable<RdSymbolInfo>
  {
    //fields
    //public fields
    [NotNull] public string Name {get; private set;}
    [NotNull] public string QualifiedName {get; private set;}
    [NotNull] public string Kind {get; private set;}
    [CanBeNull] public string FilePath {get; private set;}
    [CanBeNull] public int? Line {get; private set;}
    [CanBeNull] public int? Column {get; private set;}
    [NotNull] public string Language {get; private set;}
    [CanBeNull] public string Signature {get; private set;}
    [NotNull] public List<string> Modifiers {get; private set;}
    
    //private fields
    //primary constructor
    public RdSymbolInfo(
      [NotNull] string name,
      [NotNull] string qualifiedName,
      [NotNull] string kind,
      [CanBeNull] string filePath,
      [CanBeNull] int? line,
      [CanBeNull] int? column,
      [NotNull] string language,
      [CanBeNull] string signature,
      [NotNull] List<string> modifiers
    )
    {
      if (name == null) throw new ArgumentNullException("name");
      if (qualifiedName == null) throw new ArgumentNullException("qualifiedName");
      if (kind == null) throw new ArgumentNullException("kind");
      if (language == null) throw new ArgumentNullException("language");
      if (modifiers == null) throw new ArgumentNullException("modifiers");
      
      Name = name;
      QualifiedName = qualifiedName;
      Kind = kind;
      FilePath = filePath;
      Line = line;
      Column = column;
      Language = language;
      Signature = signature;
      Modifiers = modifiers;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string name, [NotNull] out string qualifiedName, [NotNull] out string kind, [CanBeNull] out string filePath, [CanBeNull] out int? line, [CanBeNull] out int? column, [NotNull] out string language, [CanBeNull] out string signature, [NotNull] out List<string> modifiers)
    {
      name = Name;
      qualifiedName = QualifiedName;
      kind = Kind;
      filePath = FilePath;
      line = Line;
      column = Column;
      language = Language;
      signature = Signature;
      modifiers = Modifiers;
    }
    //statics
    
    public static CtxReadDelegate<RdSymbolInfo> Read = (ctx, reader) => 
    {
      var name = reader.ReadString();
      var qualifiedName = reader.ReadString();
      var kind = reader.ReadString();
      var filePath = ReadStringNullable(ctx, reader);
      var line = ReadIntNullable(ctx, reader);
      var column = ReadIntNullable(ctx, reader);
      var language = reader.ReadString();
      var signature = ReadStringNullable(ctx, reader);
      var modifiers = ReadStringList(ctx, reader);
      var _result = new RdSymbolInfo(name, qualifiedName, kind, filePath, line, column, language, signature, modifiers);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    public static CtxReadDelegate<int?> ReadIntNullable = JetBrains.Rd.Impl.Serializers.ReadInt.NullableStruct();
    public static CtxReadDelegate<List<string>> ReadStringList = JetBrains.Rd.Impl.Serializers.ReadString.List();
    
    public static CtxWriteDelegate<RdSymbolInfo> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Name);
      writer.Write(value.QualifiedName);
      writer.Write(value.Kind);
      WriteStringNullable(ctx, writer, value.FilePath);
      WriteIntNullable(ctx, writer, value.Line);
      WriteIntNullable(ctx, writer, value.Column);
      writer.Write(value.Language);
      WriteStringNullable(ctx, writer, value.Signature);
      WriteStringList(ctx, writer, value.Modifiers);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    public static  CtxWriteDelegate<int?> WriteIntNullable = JetBrains.Rd.Impl.Serializers.WriteInt.NullableStruct();
    public static  CtxWriteDelegate<List<string>> WriteStringList = JetBrains.Rd.Impl.Serializers.WriteString.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdSymbolInfo) obj);
    }
    public bool Equals(RdSymbolInfo other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Name == other.Name && QualifiedName == other.QualifiedName && Kind == other.Kind && Equals(FilePath, other.FilePath) && Equals(Line, other.Line) && Equals(Column, other.Column) && Language == other.Language && Equals(Signature, other.Signature) && Modifiers.SequenceEqual(other.Modifiers);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Name.GetHashCode();
        hash = hash * 31 + QualifiedName.GetHashCode();
        hash = hash * 31 + Kind.GetHashCode();
        hash = hash * 31 + (FilePath != null ? FilePath.GetHashCode() : 0);
        hash = hash * 31 + (Line != null ? Line.GetHashCode() : 0);
        hash = hash * 31 + (Column != null ? Column.GetHashCode() : 0);
        hash = hash * 31 + Language.GetHashCode();
        hash = hash * 31 + (Signature != null ? Signature.GetHashCode() : 0);
        hash = hash * 31 + Modifiers.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdSymbolInfo (");
      using (printer.IndentCookie()) {
        printer.Print("name = "); Name.PrintEx(printer); printer.Println();
        printer.Print("qualifiedName = "); QualifiedName.PrintEx(printer); printer.Println();
        printer.Print("kind = "); Kind.PrintEx(printer); printer.Println();
        printer.Print("filePath = "); FilePath.PrintEx(printer); printer.Println();
        printer.Print("line = "); Line.PrintEx(printer); printer.Println();
        printer.Print("column = "); Column.PrintEx(printer); printer.Println();
        printer.Print("language = "); Language.PrintEx(printer); printer.Println();
        printer.Print("signature = "); Signature.PrintEx(printer); printer.Println();
        printer.Print("modifiers = "); Modifiers.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: IndexMcpModel.kt:48</p>
  /// </summary>
  public sealed class RdTypeHierarchyRequest : IPrintable, IEquatable<RdTypeHierarchyRequest>
  {
    //fields
    //public fields
    [NotNull] public RdSourcePosition Position {get; private set;}
    [NotNull] public string Scope {get; private set;}
    
    //private fields
    //primary constructor
    public RdTypeHierarchyRequest(
      [NotNull] RdSourcePosition position,
      [NotNull] string scope
    )
    {
      if (position == null) throw new ArgumentNullException("position");
      if (scope == null) throw new ArgumentNullException("scope");
      
      Position = position;
      Scope = scope;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out RdSourcePosition position, [NotNull] out string scope)
    {
      position = Position;
      scope = Scope;
    }
    //statics
    
    public static CtxReadDelegate<RdTypeHierarchyRequest> Read = (ctx, reader) => 
    {
      var position = RdSourcePosition.Read(ctx, reader);
      var scope = reader.ReadString();
      var _result = new RdTypeHierarchyRequest(position, scope);
      return _result;
    };
    
    public static CtxWriteDelegate<RdTypeHierarchyRequest> Write = (ctx, writer, value) => 
    {
      RdSourcePosition.Write(ctx, writer, value.Position);
      writer.Write(value.Scope);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdTypeHierarchyRequest) obj);
    }
    public bool Equals(RdTypeHierarchyRequest other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Equals(Position, other.Position) && Scope == other.Scope;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Position.GetHashCode();
        hash = hash * 31 + Scope.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdTypeHierarchyRequest (");
      using (printer.IndentCookie()) {
        printer.Print("position = "); Position.PrintEx(printer); printer.Println();
        printer.Print("scope = "); Scope.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: IndexMcpModel.kt:53</p>
  /// </summary>
  public sealed class RdTypeHierarchyResult : IPrintable, IEquatable<RdTypeHierarchyResult>
  {
    //fields
    //public fields
    [NotNull] public RdSymbolInfo Element {get; private set;}
    [NotNull] public List<RdSymbolInfo> Supertypes {get; private set;}
    [NotNull] public List<RdSymbolInfo> Subtypes {get; private set;}
    
    //private fields
    //primary constructor
    public RdTypeHierarchyResult(
      [NotNull] RdSymbolInfo element,
      [NotNull] List<RdSymbolInfo> supertypes,
      [NotNull] List<RdSymbolInfo> subtypes
    )
    {
      if (element == null) throw new ArgumentNullException("element");
      if (supertypes == null) throw new ArgumentNullException("supertypes");
      if (subtypes == null) throw new ArgumentNullException("subtypes");
      
      Element = element;
      Supertypes = supertypes;
      Subtypes = subtypes;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out RdSymbolInfo element, [NotNull] out List<RdSymbolInfo> supertypes, [NotNull] out List<RdSymbolInfo> subtypes)
    {
      element = Element;
      supertypes = Supertypes;
      subtypes = Subtypes;
    }
    //statics
    
    public static CtxReadDelegate<RdTypeHierarchyResult> Read = (ctx, reader) => 
    {
      var element = RdSymbolInfo.Read(ctx, reader);
      var supertypes = ReadRdSymbolInfoList(ctx, reader);
      var subtypes = ReadRdSymbolInfoList(ctx, reader);
      var _result = new RdTypeHierarchyResult(element, supertypes, subtypes);
      return _result;
    };
    public static CtxReadDelegate<List<RdSymbolInfo>> ReadRdSymbolInfoList = RdSymbolInfo.Read.List();
    
    public static CtxWriteDelegate<RdTypeHierarchyResult> Write = (ctx, writer, value) => 
    {
      RdSymbolInfo.Write(ctx, writer, value.Element);
      WriteRdSymbolInfoList(ctx, writer, value.Supertypes);
      WriteRdSymbolInfoList(ctx, writer, value.Subtypes);
    };
    public static  CtxWriteDelegate<List<RdSymbolInfo>> WriteRdSymbolInfoList = RdSymbolInfo.Write.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((RdTypeHierarchyResult) obj);
    }
    public bool Equals(RdTypeHierarchyResult other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Equals(Element, other.Element) && Supertypes.SequenceEqual(other.Supertypes) && Subtypes.SequenceEqual(other.Subtypes);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Element.GetHashCode();
        hash = hash * 31 + Supertypes.ContentHashCode();
        hash = hash * 31 + Subtypes.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("RdTypeHierarchyResult (");
      using (printer.IndentCookie()) {
        printer.Print("element = "); Element.PrintEx(printer); printer.Println();
        printer.Print("supertypes = "); Supertypes.PrintEx(printer); printer.Println();
        printer.Print("subtypes = "); Subtypes.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
