package com.github.hechtcarmel.jetbrainsindexmcpplugin.handlers.dotnet

import com.github.hechtcarmel.jetbrainsindexmcpplugin.constants.ErrorMessages
import com.github.hechtcarmel.jetbrainsindexmcpplugin.constants.toArgumentFailure
import com.github.hechtcarmel.jetbrainsindexmcpplugin.handlers.*
import com.github.hechtcarmel.jetbrainsindexmcpplugin.server.PaginationService
import com.github.hechtcarmel.jetbrainsindexmcpplugin.tools.models.StructureKind
import com.github.hechtcarmel.jetbrainsindexmcpplugin.tools.models.StructureNode
import com.github.hechtcarmel.jetbrainsindexmcpplugin.tools.models.DefinitionResult
import com.github.hechtcarmel.jetbrainsindexmcpplugin.tools.models.SymbolMatch
import com.github.hechtcarmel.jetbrainsindexmcpplugin.tools.models.UsageLocation
import com.github.hechtcarmel.jetbrainsindexmcpplugin.util.ProjectUtils
import com.github.hechtcarmel.jetbrainsindexmcpplugin.util.PsiUtils
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.diagnostic.logger
import com.intellij.openapi.vfs.LocalFileSystem
import com.intellij.openapi.project.Project
import com.intellij.openapi.vfs.VirtualFile
import com.intellij.psi.PsiDocumentManager
import com.intellij.psi.PsiElement
import com.intellij.psi.PsiFile
import com.intellij.psi.PsiManager
import com.intellij.psi.PsiNamedElement
import java.io.File
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit

/**
 * Rider protocol-based handlers for C# code intelligence.
 *
 * These handlers delegate to the ReSharper backend via the rd protocol model,
 * providing full semantic analysis instead of the heuristic-based approach.
 * They are only registered when running inside Rider.
 *
 * All access to the rd protocol model uses reflection because the generated
 * protocol stubs are only available in Rider's runtime classpath, not during
 * compilation against IntelliJ Community (IC).
 */
object RiderDotNetHandlers {
    private val LOG = logger<RiderDotNetHandlers>()

    @JvmStatic
    fun register(registry: LanguageHandlerRegistry) {
        if (!isRiderEnvironment()) {
            LOG.info("Not running in Rider, skipping Rider protocol handler registration")
            return
        }
        if (!isRiderProtocolGenerated()) {
            LOG.warn(
                "Rider Index MCP protocol stubs are not available. " +
                    "Skipping C# semantic handlers instead of falling back to frontend PSI heuristics."
            )
            return
        }

        // C# handlers
        registry.registerTypeHierarchyHandler(RiderCSharpTypeHierarchyHandler())
        registry.registerImplementationsHandler(RiderCSharpImplementationsHandler())
        registry.registerCallHierarchyHandler(RiderCSharpCallHierarchyHandler())
        registry.registerSuperMethodsHandler(RiderCSharpSuperMethodsHandler())
        registry.registerSymbolReferenceHandler(RiderCSharpSymbolReferenceHandler())
        registry.registerStructureHandler(RiderCSharpStructureHandler())

        LOG.info("Registered Rider protocol-based .NET handlers for C#")
    }

    private fun isRiderEnvironment(): Boolean = RiderEnvironment.isAvailable

    private fun isRiderProtocolGenerated(): Boolean = RiderEnvironment.isProtocolGenerated
}

/**
 * Cached Rider environment + protocol-stub detection. The lookups are reflection-based and
 * never change for the lifetime of the JVM, so we resolve them once via `lazy { }`.
 *
 * Using `lazy` (not eager init) avoids ordering hazards if Rider classes load late.
 */
internal object RiderEnvironment {
    val isAvailable: Boolean by lazy {
        try {
            Class.forName("com.jetbrains.rider.projectView.solution.SolutionLifecycleHost")
            true
        } catch (_: ClassNotFoundException) {
            try {
                Class.forName("com.jetbrains.rider.projectView.SolutionLifecycleHost")
                true
            } catch (_: ClassNotFoundException) {
                false
            }
        }
    }

    val isProtocolGenerated: Boolean by lazy {
        try {
            Class.forName("$MODEL_PKG.IndexMcpModel")
            Class.forName("$MODEL_PKG.IndexMcpModel_GeneratedKt")
            true
        } catch (_: ClassNotFoundException) {
            false
        }
    }
}

// ── Reflection-based rd protocol access ─────────────────────────────────────

/**
 * Wraps reflection calls to the rd protocol model.
 *
 * The IndexMcpModel extension property on IProtocol is generated by rdgen and
 * is only available at runtime inside Rider. We access it reflectively so the
 * plugin can compile against IC.
 */
object RdProtocolBridge {
    private val LOG = logger<RdProtocolBridge>()

    // Reflection caches. Keys are class-name + member signature; values are immutable per JVM lifetime.
    // ConcurrentHashMap.computeIfAbsent is safe — Method/Constructor lookups are pure functions.
    private val methodCache = java.util.concurrent.ConcurrentHashMap<String, java.lang.reflect.Method>()
    private val constructorCache = java.util.concurrent.ConcurrentHashMap<String, java.lang.reflect.Constructor<*>>()

    private fun cachedMethod(clazz: Class<*>, name: String, vararg paramTypes: Class<*>): java.lang.reflect.Method {
        val key = "${clazz.name}#$name(${paramTypes.joinToString(",") { it.name }})"
        return methodCache.computeIfAbsent(key) { clazz.getMethod(name, *paramTypes) }
    }

    private fun cachedConstructor(clazz: Class<*>, arity: Int): java.lang.reflect.Constructor<*>? {
        val key = "${clazz.name}#<init>($arity)"
        return constructorCache[key] ?: clazz.constructors.firstOrNull { it.parameterCount == arity }
            ?.also { constructorCache[key] = it }
    }

    /**
     * Gets the IndexMcpModel from a Project's Rider protocol host.
     * Returns null if Rider classes aren't available.
     */
    fun getModel(project: Project): Any? {
        getModelFromProtocolListener(project)?.let { return it }
        getModelFromSolution(project)?.let { return it }
        return try {
            // ProtocolManager.getOrCreate(project).protocol.indexMcpModel → IndexMcpModel
            val protocol = getProtocol(project) ?: return null
            val protocolClass = Class.forName("com.jetbrains.rd.framework.IProtocol")
            val modelExtClass = Class.forName("com.jetbrains.rd.ide.model.IndexMcpModel_GeneratedKt")
            val getModel = modelExtClass.getMethod("getIndexMcpModel", protocolClass)
            getModel.invoke(null, protocol)
        } catch (e: Exception) {
            LOG.warn("Failed to get IndexMcpModel via reflection: ${e.message}")
            null
        }
    }

    private fun getModelFromSolution(project: Project): Any? {
        return try {
            val solutionHostExtensions = Class.forName("com.jetbrains.rider.projectView.SolutionHostExtensionsKt")
            val solution = solutionHostExtensions.getMethod("getSolution", Project::class.java).invoke(null, project)
                ?: return null
            val solutionClass = Class.forName("com.jetbrains.rd.ide.model.Solution")
            val modelExtClass = Class.forName("com.jetbrains.rd.ide.model.IndexMcpModel_GeneratedKt")
            val getModel = modelExtClass.getMethod("getIndexMcpModel", solutionClass)
            getModel.invoke(null, solution)
        } catch (e: Exception) {
            LOG.debug("Failed to get solution-scoped IndexMcpModel via reflection: ${e.message}")
            null
        }
    }

    private fun getModelFromProtocolListener(project: Project): Any? {
        return try {
            val storeClass = Class.forName("com.jetbrains.rider.plugins.indexmcp.IndexMcpProtocolModelStore")
            val get = storeClass.getMethod("get", Project::class.java)
            get.invoke(null, project)
        } catch (e: Exception) {
            LOG.debug("IndexMcpProtocolModelStore is not available: ${e.message}")
            null
        }
    }

    private fun getProtocol(project: Project): Any? {
        val protocolManagerClass = Class.forName("com.jetbrains.rider.protocol.ProtocolManager")
        val protocolManager = ApplicationManager.getApplication().getService(protocolManagerClass) ?: return null
        val getOrCreate = protocolManagerClass.getMethod("getOrCreate", Project::class.java)
        val protocolHost = getOrCreate.invoke(protocolManager, project) ?: return null
        return protocolHost.javaClass.getMethod("getProtocol").invoke(protocolHost)
    }

    /**
     * Invokes a named RdCall on the model synchronously.
     *
     * @param model The IndexMcpModel instance
     * @param callName The RPC method name (e.g., "getTypeHierarchy")
     * @param request The request object (an rd structdef instance)
     * @return The response object, or null
     */
    fun invokeCall(model: Any, callName: String, request: Any): Any? {
        return when (val outcome = invokeCallResult(model, callName, request)) {
            is RdCallOutcome.Success -> outcome.value
            is RdCallOutcome.Timeout -> {
                LOG.warn("Timed out waiting for Rider backend rd call '${outcome.callName}' after ${outcome.timeoutSeconds}s")
                null
            }
            is RdCallOutcome.Failure -> {
                LOG.warn(
                    "Failed to invoke rd call '$callName': ${outcome.cause::class.java.simpleName}: ${outcome.cause.message}"
                )
                null
            }
        }
    }

    fun invokeCallResult(model: Any, callName: String, request: Any): RdCallOutcome<Any?> {
        return try {
            val callField = cachedMethod(model.javaClass, "get${callName.replaceFirstChar { it.uppercaseChar() }}")
            val rdCall = callField.invoke(model)
            val protocol = cachedMethod(model.javaClass, "getProtocol").invoke(model)
            var lifetime = cachedMethod(protocol.javaClass, "getLifetime").invoke(protocol)
            val lifetimeClass = Class.forName("com.jetbrains.rd.util.lifetime.Lifetime")
            if (!lifetimeClass.isInstance(lifetime)) {
                lifetime = cachedMethod(lifetime.javaClass, "getLifetime").invoke(lifetime)
            }
            val scheduler = cachedMethod(protocol.javaClass, "getScheduler").invoke(protocol)
            val resultLatch = CountDownLatch(1)
            var taskResult: Any? = null
            var failure: Throwable? = null
            val startRequest: () -> Unit = {
                try {
                    val startMethod = cachedMethod(rdCall.javaClass, "start", Any::class.java)
                    val rdTask = startMethod.invoke(rdCall, request)
                    val resultView = cachedMethod(rdTask.javaClass, "getResult").invoke(rdTask)
                    taskResult = cachedMethod(resultView.javaClass, "getValueOrNull").invoke(resultView)
                    if (taskResult == null) {
                        val callback: (Any?) -> Unit = {
                            taskResult = it
                            resultLatch.countDown()
                        }
                        cachedMethod(resultView.javaClass, "advise", lifetimeClass, kotlin.jvm.functions.Function1::class.java)
                            .invoke(resultView, lifetime, callback)
                    } else {
                        resultLatch.countDown()
                    }
                } catch (e: Throwable) {
                    failure = e
                    resultLatch.countDown()
                }
            }
            val isActive = cachedMethod(scheduler.javaClass, "isActive").invoke(scheduler) as Boolean
            if (isActive) {
                startRequest()
            } else {
                cachedMethod(scheduler.javaClass, "queue", kotlin.jvm.functions.Function0::class.java)
                    .invoke(scheduler, startRequest)
            }
            val timeoutSeconds = timeoutSecondsForCall(callName)
            if (!resultLatch.await(timeoutSeconds, TimeUnit.SECONDS)) {
                return RdCallOutcome.Timeout(callName = callName, timeoutSeconds = timeoutSeconds)
            }
            failure?.let { return RdCallOutcome.Failure(callName = callName, cause = it) }
            RdCallOutcome.Success(unwrapRdTaskResult(taskResult))
        } catch (e: Exception) {
            val cause = (e as? java.lang.reflect.InvocationTargetException)?.targetException ?: e.cause ?: e
            RdCallOutcome.Failure(callName = callName, cause = cause)
        }
    }

    internal fun timeoutSecondsForCall(callName: String): Long = when (callName) {
        "renameSymbol" -> 300L
        "getCallHierarchy" -> 30L
        else -> 60L
    }

    private fun unwrapRdTaskResult(taskResult: Any?): Any? {
        if (taskResult == null) {
            return null
        }
        return when (taskResult.javaClass.simpleName) {
            "Success" -> taskResult.javaClass.getMethod("getValue").invoke(taskResult)
            "Fault" -> {
                val error = taskResult.javaClass.getMethod("getError").invoke(taskResult)
                throw IllegalStateException(error.toString())
            }
            "Cancelled" -> throw IllegalStateException("Rider backend rd call was cancelled")
            else -> throw IllegalStateException("Unexpected Rider backend rd task result: ${taskResult.javaClass.name}")
        }
    }

    /**
     * Creates an rd struct instance via its constructor reflectively.
     *
     * Returns null when no constructor matches the supplied arity. Previous behaviour fell back to
     * `clazz.constructors.first()` on no match, which would invoke an arbitrary constructor with
     * mismatched arguments and throw deep inside reflection — masking the real cause from callers.
     */
    fun createStruct(className: String, vararg args: Any?): Any? {
        return try {
            val clazz = Class.forName(className)
            val constructor = cachedConstructor(clazz, args.size)
            if (constructor == null) {
                val available = clazz.constructors.joinToString { "(${it.parameterCount} args)" }
                LOG.warn("No constructor on '$className' matches arity ${args.size}. Available: $available")
                return null
            }
            constructor.newInstance(*args)
        } catch (e: Exception) {
            LOG.warn("Failed to create rd struct '$className': ${e.message}")
            null
        }
    }

    /** Gets a property value from an rd struct via JavaBean getter. */
    fun getProperty(obj: Any, name: String): Any? {
        return try {
            val getter = cachedMethod(obj.javaClass, "get${name.replaceFirstChar { it.uppercaseChar() }}")
            getter.invoke(obj)
        } catch (e: Exception) {
            LOG.debug("Failed to get property '$name' from ${obj.javaClass.simpleName}: ${e.message}")
            null
        }
    }
}

const val MODEL_PKG = "com.jetbrains.rd.ide.model"

data class RiderBackendResponse<T>(
    val handled: Boolean,
    val value: T? = null,
    val errorMessage: String? = null,
    val message: String? = null
)

sealed interface RdCallOutcome<out T> {
    data class Success<T>(val value: T) : RdCallOutcome<T>
    data class Timeout(val callName: String, val timeoutSeconds: Long) : RdCallOutcome<Nothing>
    data class Failure(val callName: String, val cause: Throwable) : RdCallOutcome<Nothing>
}

internal fun RdCallOutcome.Timeout.toUserMessage(operation: String): String =
    "Rider backend timed out while $operation after ${timeoutSeconds}s (rd call '$callName')."

internal fun RdCallOutcome.Failure.toUserMessage(operation: String): String {
    val rawDetail = cause.message?.takeIf { it.isNotBlank() } ?: cause.toString()
    val detail = sanitizeBackendDiagnostic(rawDetail)
    if (detail.contains("requires warmed ReSharper usage caches", ignoreCase = false)) {
        return detail
    }
    return "Rider backend failed while $operation (rd call '$callName'): $detail"
}

/**
 * Strip backend-internal noise (stack frames, absolute backend source paths, `at NS.Method(...)`
 * lines) from a diagnostic message before surfacing it to the MCP client. Keeps the first line,
 * which is typically the human-readable cause, and removes any trailing technical noise.
 *
 * Defense in depth: even when the backend converts an unresolved-target into a graceful
 * `message` field (the v4.20.0+ contract), any unexpected exception that escapes through
 * `RdFault.cause.message` would otherwise leak `IndexMcpBackendHost.cs:line N` style frames.
 */
internal fun sanitizeBackendDiagnostic(detail: String): String {
    val firstLine = detail.lineSequence().firstOrNull()?.trim().orEmpty()
    if (firstLine.isEmpty()) return detail.trim()

    // Remove inline " at NS.Method(...)" segments and trailing ":line N" markers.
    val cleaned = firstLine
        .replace(Regex("""\s+at\s+[\w.<>+`]+\([^)]*\)(\s+in\s+[^:]+:line\s+\d+)?"""), "")
        .replace(Regex(""":line\s+\d+"""), "")
        .replace(Regex("""(?:[A-Za-z]:\\|/)[^\s:]*[\\/][\w.+-]+\.(?:cs|kt|java)(?::\d+)?"""), "<backend>")
        .trim()
    return if (cleaned.isEmpty()) firstLine else cleaned
}

internal class RiderBackendTimeoutException(
    val callName: String,
    val timeoutSeconds: Long,
    operation: String
) : IllegalStateException(RdCallOutcome.Timeout(callName, timeoutSeconds).toUserMessage(operation))

internal data class RiderBackendSymbolResult(
    val status: String,
    val message: String?,
    val symbolInfo: Any?
)

internal data class RiderBackendVerificationResult(
    val status: String?,
    val checksRun: List<String>,
    val warnings: List<String>
)

internal data class RiderBackendRenameDiagnostics(
    val resolutionStatus: String?,
    val targetKind: String?,
    val resolvedName: String?,
    val sourceTokenText: String?,
    val executionHint: String?,
    val unsupportedReason: String?,
    val traceStages: List<String>
)

internal data class RiderBackendMutationResult(
    val success: Boolean,
    val status: String?,
    val message: String?,
    val affectedFiles: List<String>,
    val changesCount: Int,
    val verification: RiderBackendVerificationResult?,
    val renameDiagnostics: RiderBackendRenameDiagnostics?
)

internal object RiderBackendMutationResultMapper {
    private const val RENAME_DIAGNOSTICS_PREFIX = "[backendSymbolRename:"
    private val renameDiagnosticsEntryRegex = Regex("""(?:^|,\s*)([A-Za-z][A-Za-z0-9]*)=(.*?)(?=,\s*[A-Za-z][A-Za-z0-9]*=|$)""")

    fun fromRdResult(result: Any): RiderBackendMutationResult {
        val rawMessage = RdProtocolBridge.getProperty(result, "message") as? String
        val parsedMessage = parseRenameDiagnostics(rawMessage)
        val verification = parseVerification(RdProtocolBridge.getProperty(result, "verification"))
        @Suppress("UNCHECKED_CAST")
        val affectedFiles = (RdProtocolBridge.getProperty(result, "affectedFiles") as? List<String>) ?: emptyList()

        return RiderBackendMutationResult(
            success = RdProtocolBridge.getProperty(result, "success") as? Boolean ?: false,
            status = RdProtocolBridge.getProperty(result, "status") as? String,
            message = parsedMessage.userMessage,
            affectedFiles = affectedFiles,
            changesCount = RdProtocolBridge.getProperty(result, "changesCount") as? Int ?: 0,
            verification = verification,
            renameDiagnostics = parsedMessage.renameDiagnostics
        )
    }

    private fun parseVerification(verification: Any?): RiderBackendVerificationResult? {
        verification ?: return null
        @Suppress("UNCHECKED_CAST")
        val checksRun = (RdProtocolBridge.getProperty(verification, "checksRun") as? List<String>) ?: emptyList()
        @Suppress("UNCHECKED_CAST")
        val warnings = (RdProtocolBridge.getProperty(verification, "warnings") as? List<String>) ?: emptyList()
        return RiderBackendVerificationResult(
            status = RdProtocolBridge.getProperty(verification, "status") as? String,
            checksRun = checksRun,
            warnings = warnings
        )
    }

    private fun parseRenameDiagnostics(message: String?): ParsedRiderBackendMessage {
        if (message.isNullOrBlank()) {
            return ParsedRiderBackendMessage(message, null)
        }

        val markerIndex = message.lastIndexOf(RENAME_DIAGNOSTICS_PREFIX)
        if (markerIndex < 0 || !message.endsWith(']')) {
            return ParsedRiderBackendMessage(message, null)
        }

        val userMessage = message.substring(0, markerIndex).trimEnd().ifBlank { null }
        val payload = message.substring(markerIndex + RENAME_DIAGNOSTICS_PREFIX.length, message.length - 1).trim()
        val entries = renameDiagnosticsEntryRegex.findAll(payload)
            .associate { match ->
                match.groupValues[1] to match.groupValues[2].trim()
            }

        val diagnostics = RiderBackendRenameDiagnostics(
            resolutionStatus = entries["resolutionStatus"].normalizedDiagnosticValue(),
            targetKind = entries["targetKind"].normalizedDiagnosticValue(),
            resolvedName = entries["resolvedName"].normalizedDiagnosticValue(),
            sourceTokenText = entries["sourceTokenText"].normalizedDiagnosticValue(),
            executionHint = entries["executionHint"].normalizedDiagnosticValue(),
            unsupportedReason = entries["unsupportedReason"].normalizedDiagnosticValue(),
            traceStages = entries["traceStages"].normalizedDiagnosticValue()
                ?.split('>')
                ?.map { it.trim() }
                ?.filter { it.isNotEmpty() }
                ?: emptyList()
        )

        return ParsedRiderBackendMessage(userMessage, diagnostics)
    }

    private fun String?.normalizedDiagnosticValue(): String? =
        this?.takeUnless { it.isBlank() || it == "<null>" }

    private data class ParsedRiderBackendMessage(
        val userMessage: String?,
        val renameDiagnostics: RiderBackendRenameDiagnostics?
    )
}

object RiderBackendSemanticService {
    private val LOG = logger<RiderBackendSemanticService>()

    fun isRiderEnvironment(): Boolean = RiderEnvironment.isAvailable

    private fun canHandleLanguage(language: String?): Boolean =
        language == null || isAcceptedLanguageAlias(language, CSHARP_LANGUAGE_IDS)

    fun isDotNetFile(file: String?): Boolean {
        val ext = file?.substringAfterLast('.', missingDelimiterValue = "")?.lowercase()
        return ext in CSHARP_EXTENSIONS
    }

    fun findTypes(
        project: Project,
        query: String,
        matchMode: String,
        scope: BuiltInSearchScope,
        language: String?,
        limit: Int
    ): RiderBackendResponse<List<SymbolMatch>> {
        if (!canUseBackend(project) || !canHandleLanguage(language)) return RiderBackendResponse(handled = false)
        val model = RdProtocolBridge.getModel(project) ?: return RiderBackendResponse(handled = true)
        val request = RdProtocolBridge.createStruct(
            "$MODEL_PKG.RdFindTypesRequest",
            query,
            matchMode,
            scope.wireValue,
            language,
            limit
        ) ?: return RiderBackendResponse(handled = true)
        val result = RdProtocolBridge.invokeCall(model, "findTypes", request) ?: return RiderBackendResponse(handled = true)
        @Suppress("UNCHECKED_CAST")
        val types = (RdProtocolBridge.getProperty(result, "types") as? List<Any>) ?: emptyList()
        // Backend already merges BCL/standard types into its response when scope = PROJECT_AND_LIBRARIES,
        // so no frontend-side append/merge is required. See `IndexMcpBackendHost.cs` STANDARD_DOTNET_TYPES.
        return RiderBackendResponse(
            handled = true,
            value = types.mapNotNull { rdSymbolToSymbolMatch(project, it) }
                .distinctBy { "${it.qualifiedName}:${it.file}:${it.line}" }
                .take(limit)
        )
    }

    fun findSymbols(
        project: Project,
        query: String,
        scope: BuiltInSearchScope,
        language: String?,
        limit: Int
    ): RiderBackendResponse<List<SymbolMatch>> {
        val normalizedLanguage = normalizeAcceptedCSharpAlias(language)
        if (!canUseBackend(project) || normalizedLanguage != CSHARP_CANONICAL_LANGUAGE_ID) {
            return RiderBackendResponse(handled = false)
        }

        val model = RdProtocolBridge.getModel(project) ?: return RiderBackendResponse(handled = true)
        val request = RdProtocolBridge.createStruct(
            "$MODEL_PKG.RdFindSymbolsRequest",
            query,
            scope.wireValue,
            normalizedLanguage,
            limit
        ) ?: return RiderBackendResponse(handled = true)
        val result = RdProtocolBridge.invokeCall(model, "findSymbols", request) ?: return RiderBackendResponse(handled = true)
        @Suppress("UNCHECKED_CAST")
        val symbols = (RdProtocolBridge.getProperty(result, "symbols") as? List<Any>) ?: emptyList()

        return RiderBackendResponse(
            handled = true,
            value = symbols.mapNotNull { rdSymbolToSymbolMatch(project, it) }
                .distinctBy { "${it.qualifiedName}:${it.file}:${it.line}:${it.column}" }
                .take(limit)
        )
    }

    fun findDefinition(
        project: Project,
        file: String?,
        line: Int?,
        column: Int?,
        language: String?,
        symbol: String?,
        fullElementPreview: Boolean,
        maxPreviewLines: Int
    ): RiderBackendResponse<DefinitionResult> {
        val positionTarget = file != null && line != null && column != null && isDotNetFile(file)
        val symbolTarget = language != null && symbol != null && canHandleLanguage(language)
        if (!canUseBackend(project) || (!positionTarget && !symbolTarget)) return RiderBackendResponse(handled = false)

        val semanticTarget = buildSemanticTarget(project, file, line, column, language, symbol)
        semanticTarget.errorMessage?.let { return RiderBackendResponse(handled = true, errorMessage = it) }
        val target = semanticTarget.target ?: return RiderBackendResponse(handled = true)
        val model = RdProtocolBridge.getModel(project) ?: return RiderBackendResponse(handled = true)
        val request = RdProtocolBridge.createStruct(
            "$MODEL_PKG.RdFindDefinitionRequest",
            target,
            fullElementPreview,
            maxPreviewLines
        ) ?: return RiderBackendResponse(handled = true)
        val result = RdProtocolBridge.invokeCall(model, "findDefinition", request) ?: return RiderBackendResponse(handled = true)
        val definition = RdProtocolBridge.getProperty(result, "definition") ?: return RiderBackendResponse(handled = true)
        @Suppress("UNCHECKED_CAST")
        val astPath = (RdProtocolBridge.getProperty(result, "astPath") as? List<String>) ?: emptyList()
        val locationKind =
            (RdProtocolBridge.getProperty(result, "locationKind") as? String)
                ?: (RdProtocolBridge.getProperty(definition, "locationKind") as? String)
        val locationDisplayName =
            (RdProtocolBridge.getProperty(result, "locationDisplayName") as? String)
                ?: (RdProtocolBridge.getProperty(definition, "locationDisplayName") as? String)
        val message = riderDefinitionMessage(
            symbolName = RdProtocolBridge.getProperty(definition, "name") as? String ?: "unknown",
            locationKind = locationKind,
            locationDisplayName = locationDisplayName
        )
        return RiderBackendResponse(
            handled = true,
            value = DefinitionResult(
                file = displayPath(project, RdProtocolBridge.getProperty(definition, "filePath") as? String),
                line = RdProtocolBridge.getProperty(definition, "line") as? Int ?: 1,
                column = RdProtocolBridge.getProperty(definition, "column") as? Int ?: 1,
                preview = riderDefinitionPreview(
                    preview = RdProtocolBridge.getProperty(result, "preview") as? String ?: "",
                    message = message
                ),
                symbolName = RdProtocolBridge.getProperty(definition, "name") as? String ?: "unknown",
                astPath = astPath,
                message = message,
                locationKind = locationKind,
                locationDisplayName = locationDisplayName
            ),
            message = message
        )
    }

    fun findReferences(
        project: Project,
        file: String?,
        line: Int?,
        column: Int?,
        language: String?,
        symbol: String?,
        scope: BuiltInSearchScope,
        limit: Int
    ): RiderBackendResponse<List<UsageLocation>> {
        val positionTarget = file != null && line != null && column != null && isDotNetFile(file)
        val symbolTarget = language != null && symbol != null && canHandleLanguage(language)
        if (!canUseBackend(project) || (!positionTarget && !symbolTarget)) return RiderBackendResponse(handled = false)

        val semanticTarget = buildSemanticTarget(project, file, line, column, language, symbol)
        semanticTarget.errorMessage?.let { return RiderBackendResponse(handled = true, errorMessage = it) }
        val target = semanticTarget.target ?: return RiderBackendResponse(handled = true)
        val model = RdProtocolBridge.getModel(project) ?: return RiderBackendResponse(handled = true)
        val request = RdProtocolBridge.createStruct("$MODEL_PKG.RdFindReferencesRequest", target, scope.wireValue, limit)
            ?: return RiderBackendResponse(handled = true)
        val result = when (val outcome = RdProtocolBridge.invokeCallResult(model, "findReferences", request)) {
            is RdCallOutcome.Success -> outcome.value ?: return RiderBackendResponse(handled = true)
            is RdCallOutcome.Timeout -> {
                return RiderBackendResponse(
                    handled = true,
                    errorMessage = outcome.toUserMessage("finding references")
                )
            }
            is RdCallOutcome.Failure -> {
                return RiderBackendResponse(
                    handled = true,
                    errorMessage = outcome.toUserMessage("finding references")
                )
            }
        }
        @Suppress("UNCHECKED_CAST")
        val references = (RdProtocolBridge.getProperty(result, "references") as? List<Any>) ?: emptyList()
        val message = RdProtocolBridge.getProperty(result, "message") as? String
        if (references.isEmpty() && !message.isNullOrBlank()) {
            return RiderBackendResponse(handled = true, errorMessage = sanitizeBackendDiagnostic(message))
        }
        val orderedDistinctReferences = references.map { reference ->
            UsageLocation(
                file = displayPath(project, RdProtocolBridge.getProperty(reference, "filePath") as? String),
                line = RdProtocolBridge.getProperty(reference, "line") as? Int ?: 1,
                column = RdProtocolBridge.getProperty(reference, "column") as? Int ?: 1,
                context = RdProtocolBridge.getProperty(reference, "context") as? String ?: "",
                type = RdProtocolBridge.getProperty(reference, "kind") as? String ?: "reference",
                astPath = (RdProtocolBridge.getProperty(reference, "astPath") as? List<String>) ?: emptyList()
            )
        }.distinctAndOrderUsageLocations()
            .take(limit)
        return RiderBackendResponse(handled = true, value = orderedDistinctReferences, message = message)
    }

    fun getCallHierarchy(
        project: Project,
        file: String?,
        line: Int?,
        column: Int?,
        language: String?,
        symbol: String?,
        direction: String,
        depth: Int,
        scope: BuiltInSearchScope
    ): RiderBackendResponse<CallHierarchyData> {
        val positionTarget = file != null && line != null && column != null && isDotNetFile(file)
        val symbolTarget = language != null && symbol != null && canHandleLanguage(language)
        if (!canUseBackend(project) || (!positionTarget && !symbolTarget)) return RiderBackendResponse(handled = false)

        val semanticTarget = buildSemanticTarget(project, file, line, column, language, symbol)
        semanticTarget.errorMessage?.let { return RiderBackendResponse(handled = true, errorMessage = it) }
        val target = semanticTarget.target ?: return RiderBackendResponse(
            handled = true,
            errorMessage = symbolTarget.thenUnsupportedCallHierarchy()
        )
        val model = RdProtocolBridge.getModel(project)
            ?: return RiderBackendResponse(
                handled = true,
                errorMessage = symbolTarget.thenUnsupportedCallHierarchy()
            )
        val displayLanguage = language?.trim()?.takeIf { it.isNotEmpty() } ?: "C#"
        return invokeSemanticCallHierarchy(project, model, target, direction, depth, scope, symbolTarget, displayLanguage)
    }

    fun getTypeHierarchy(
        project: Project,
        file: String,
        line: Int,
        column: Int,
        scope: BuiltInSearchScope,
        language: String
    ): RiderBackendResponse<TypeHierarchyData> {
        if (!canUseBackend(project) || !isDotNetFile(file)) return RiderBackendResponse(handled = false)
        val backendFile = resolveBackendFilePath(project, file) ?: return RiderBackendResponse(handled = true)
        val position = RdProtocolBridge.createStruct("$MODEL_PKG.RdSourcePosition", backendFile, line, column)
            ?: return RiderBackendResponse(handled = true)
        val result = invokeTypeHierarchy(project, position, scope) ?: return RiderBackendResponse(handled = true)
        return RiderBackendResponse(handled = true, value = rdTypeHierarchyToData(project, result, language))
    }

    /**
     * Resolve a (language, symbol) pair to a (file, line, column) position via the
     * Rider backend's symbol resolver, returning null if it couldn't be resolved or
     * if the backend is unavailable. Used by CallHierarchyTool to satisfy symbol-
     * form requests for C# without going through the Java-only
     * `LanguageHandlerRegistry.getSymbolReferenceHandlerByLanguageName` path.
     */
    fun resolveSymbolToPosition(project: Project, language: String, symbol: String): Triple<String, Int, Int>? {
        val resolution = resolveIndexedSymbol(project, language, symbol) ?: return null
        val symbolInfo = resolution.symbolInfo ?: return null
        val backendPath = RdProtocolBridge.getProperty(symbolInfo, "filePath") as? String ?: return null
        if (backendPath.isBlank()) return null
        val displayedPath = displayPath(project, backendPath)
        val line = RdProtocolBridge.getProperty(symbolInfo, "line") as? Int ?: return null
        val column = RdProtocolBridge.getProperty(symbolInfo, "column") as? Int ?: return null
        return Triple(displayedPath, line, column)
    }

    internal fun resolveIndexedSymbol(project: Project, language: String, symbol: String): RiderBackendSymbolResult? {
        if (!canUseBackend(project) || !canHandleLanguage(language)) return null
        val parsed = RiderSymbolParser.parse(language, symbol).getOrNull() ?: return null
        val model = RdProtocolBridge.getModel(project) ?: return null
        val request = RdProtocolBridge.createStruct(
            "$MODEL_PKG.RdResolveSymbolIndexedRequest",
            language,
            parsed.normalizedSymbol
        ) ?: return null
        val result = RdProtocolBridge.invokeCall(model, "resolveSymbolIndexed", request) ?: return null
        val status = RdProtocolBridge.getProperty(result, "status") as? String ?: return null
        return RiderBackendSymbolResult(
            status = status,
            message = RdProtocolBridge.getProperty(result, "message") as? String,
            symbolInfo = RdProtocolBridge.getProperty(result, "symbolInfo")
        )
    }

    private fun canUseBackend(project: Project): Boolean =
        try {
            Class.forName("$MODEL_PKG.IndexMcpModel")
            Class.forName("$MODEL_PKG.IndexMcpModel_GeneratedKt")
            RdProtocolBridge.getModel(project) != null
        } catch (e: Exception) {
            LOG.debug("Rider backend semantic service unavailable: ${e.message}")
            false
        }

    private fun createSemanticTarget(
        project: Project,
        file: String?,
        line: Int?,
        column: Int?,
        language: String?,
        symbol: String?
    ): Any? = buildSemanticTarget(project, file, line, column, language, symbol).target

    private fun buildSemanticTarget(
        project: Project,
        file: String?,
        line: Int?,
        column: Int?,
        language: String?,
        symbol: String?
    ): RiderSemanticTargetBuildResult {
        val normalizedFile = file?.trim()?.takeIf { it.isNotEmpty() }
        val normalizedLanguage = language?.trim()?.takeIf { it.isNotEmpty() }
        val normalizedSymbol = symbol?.trim()?.takeIf { it.isNotEmpty() }
        val hasPositionInput = normalizedFile != null || line != null || column != null
        val backendFile = normalizedFile?.let { resolveBackendFilePath(project, it) }

        if (backendFile != null && line != null && column != null) {
            return RiderSemanticTargetBuildResult(
                target = RdProtocolBridge.createStruct(
                    "$MODEL_PKG.RdSemanticTarget",
                    backendFile,
                    line,
                    column,
                    null,
                    null
                )
            )
        }

        if (normalizedLanguage != null && normalizedSymbol != null) {
            return RiderSemanticTargetBuildResult(
                target = RdProtocolBridge.createStruct(
                    "$MODEL_PKG.RdSemanticTarget",
                    null,
                    null,
                    null,
                    normalizedLanguage,
                    normalizedSymbol
                )
            )
        }

        if (hasPositionInput) {
            return RiderSemanticTargetBuildResult(
                errorMessage = buildUnresolvablePositionMessage(normalizedFile, line, column)
            )
        }

        return RiderSemanticTargetBuildResult(
            target = RdProtocolBridge.createStruct(
                "$MODEL_PKG.RdSemanticTarget",
                backendFile,
                line,
                column,
                normalizedLanguage,
                normalizedSymbol
            )
        )
    }

    private fun buildUnresolvablePositionMessage(file: String?, line: Int?, column: Int?): String {
        val targetLabel = listOfNotNull(file, line?.toString(), column?.toString())
            .takeIf { it.isNotEmpty() }
            ?.joinToString(":")
            ?: "<unknown>"
        return "Rider C# position target '$targetLabel' could not be mapped to a Rider source file. " +
            "Dependency-backed or source-less positions should use a language+symbol target when available."
    }

    private fun resolveBackendFilePath(project: Project, file: String): String? {
        val direct = File(file)
        if (direct.isAbsolute && direct.exists()) return direct.canonicalPath

        val roots = listOfNotNull(project.basePath) + ProjectUtils.getModuleContentRoots(project)
        for (root in roots) {
            val candidate = File(root, file)
            if (candidate.exists()) return candidate.canonicalPath
        }
        return null
    }

    internal fun invokeTypeHierarchy(project: Project, position: Any, scope: BuiltInSearchScope): Any? {
        val model = RdProtocolBridge.getModel(project) ?: return null
        val request = RdProtocolBridge.createStruct("$MODEL_PKG.RdTypeHierarchyRequest", position, scope.wireValue)
            ?: return null
        return RdProtocolBridge.invokeCall(model, "getTypeHierarchy", request)
    }

    internal fun rdTypeHierarchyToData(project: Project, result: Any, language: String): TypeHierarchyData? {
        val elementInfo = RdProtocolBridge.getProperty(result, "element") ?: return null
        @Suppress("UNCHECKED_CAST")
        val supertypes = (RdProtocolBridge.getProperty(result, "supertypes") as? List<Any>) ?: emptyList()
        @Suppress("UNCHECKED_CAST")
        val subtypes = (RdProtocolBridge.getProperty(result, "subtypes") as? List<Any>) ?: emptyList()

        return TypeHierarchyData(
            element = rdSymbolToTypeElementData(project, elementInfo, language),
            supertypes = supertypes.map { rdSymbolToTypeElementData(project, it, language) },
            subtypes = subtypes.map { rdSymbolToTypeElementData(project, it, language) }
        )
    }

    private fun rdSymbolToSymbolMatch(project: Project, symbol: Any): SymbolMatch? {
        val name = RdProtocolBridge.getProperty(symbol, "name") as? String ?: return null
        val filePath = RdProtocolBridge.getProperty(symbol, "filePath") as? String
        val qualifiedName = RdProtocolBridge.getProperty(symbol, "qualifiedName") as? String
        return SymbolMatch(
            name = name,
            qualifiedName = qualifiedName,
            kind = (RdProtocolBridge.getProperty(symbol, "kind") as? String ?: "UNKNOWN").lowercase(),
            file = filePath?.let { displayPath(project, it) } ?: "",
            line = RdProtocolBridge.getProperty(symbol, "line") as? Int ?: 0,
            column = RdProtocolBridge.getProperty(symbol, "column") as? Int ?: 0,
            containerName = qualifiedName?.substringBeforeLast('.', missingDelimiterValue = ""),
            language = RdProtocolBridge.getProperty(symbol, "language") as? String
        )
    }
}

private data class RiderSemanticTargetBuildResult(
    val target: Any? = null,
    val errorMessage: String? = null
)

internal const val RIDER_CALL_HIERARCHY_SYMBOL_MODE_UNSUPPORTED =
    "Rider C# symbol-mode call hierarchy requires the Rider backend-native path and is unsupported when that backend cannot resolve a callable semantic target."

private fun Boolean.thenUnsupportedCallHierarchy(): String? =
    if (this) RIDER_CALL_HIERARCHY_SYMBOL_MODE_UNSUPPORTED else null

// ── Helper functions ────────────────────────────────────────────────────────

private val CSHARP_EXTENSIONS = setOf("cs", "csx")
internal const val CSHARP_CANONICAL_LANGUAGE_ID = "C#"
private val CSHARP_LANGUAGE_IDS = setOf("C#", "CSHARP", "CSharp")
internal const val IMPLEMENTATIONS_RESULT_LIMIT = PaginationService.DEFAULT_OVERCOLLECT
internal const val CALL_HIERARCHY_RESULT_LIMIT = 20
internal const val CALL_HIERARCHY_EXPANDED_CHILDREN_PER_NODE_LIMIT = 5

internal fun normalizeAcceptedRiderLanguageAlias(language: String?): String? =
    language?.takeIf { it.isNotBlank() }?.let {
        when {
            isAcceptedLanguageAlias(it, CSHARP_LANGUAGE_IDS) -> CSHARP_CANONICAL_LANGUAGE_ID
            else -> it
        }
    }

internal fun normalizeAcceptedCSharpAlias(language: String?): String? =
    normalizeAcceptedRiderLanguageAlias(language)?.let {
        if (it == CSHARP_CANONICAL_LANGUAGE_ID) it else language?.takeIf(String::isNotBlank)
    }

private fun isAcceptedLanguageAlias(language: String, aliases: Set<String>): Boolean =
    aliases.any { it.equals(language, ignoreCase = true) }

private fun riderBackendPath(file: VirtualFile): String =
    file.path.replace('/', File.separatorChar)

private fun isDotNetElement(element: PsiElement, supportedExtensions: Set<String>, supportedLanguageIds: Set<String>): Boolean {
    val langId = element.language.id
    if (supportedLanguageIds.any { it.equals(langId, ignoreCase = true) }) return true
    val ext = element.containingFile?.virtualFile?.extension?.lowercase()
    return ext in supportedExtensions
}

private fun createSourcePosition(project: Project, element: PsiElement): Any? {
    val file = element.containingFile
    val vf = file?.virtualFile
    val filePath = vf?.let { riderBackendPath(it) } ?: ""
    val document = file?.let { PsiDocumentManager.getInstance(project).getDocument(it) }
    val offset = element.textOffset
    val line = document?.getLineNumber(offset)?.plus(1) ?: 1
    val column = document?.let { offset - it.getLineStartOffset(it.getLineNumber(offset)) + 1 } ?: 1
    return RdProtocolBridge.createStruct("$MODEL_PKG.RdSourcePosition", filePath, line, column)
}

private fun findNamedElementAtPosition(project: Project, filePath: String, line: Int, column: Int): PsiNamedElement? {
    val virtualFile = resolveProjectOrAbsoluteFile(project, filePath) ?: return null
    val psiFile = PsiManager.getInstance(project).findFile(virtualFile) ?: return null
    val document = PsiDocumentManager.getInstance(project).getDocument(psiFile) ?: return null
    val lineIndex = line - 1
    if (lineIndex !in 0 until document.lineCount) return null
    val lineStart = document.getLineStartOffset(lineIndex)
    val lineEnd = document.getLineEndOffset(lineIndex)
    val rawOffset = lineStart + (column - 1).coerceAtLeast(0)
    val safeOffset = rawOffset.coerceIn(lineStart, lineEnd.coerceAtLeast(lineStart))
    val leaf = psiFile.findElementAt(safeOffset)
        ?: psiFile.findElementAt((safeOffset - 1).coerceAtLeast(0))
        ?: return null
    return PsiUtils.findNamedElement(leaf)
}

private fun resolveProjectOrAbsoluteFile(project: Project, filePath: String): VirtualFile? {
    val normalized = filePath.replace('\\', File.separatorChar).replace('/', File.separatorChar)
    LocalFileSystem.getInstance().findFileByPath(normalized)?.let { return it }
    File(normalized).takeIf { it.isAbsolute && it.exists() }?.canonicalPath?.let {
        return LocalFileSystem.getInstance().findFileByPath(it)
    }
    val roots = listOfNotNull(project.basePath) + ProjectUtils.getModuleContentRoots(project)
    for (root in roots) {
        val candidate = File(root, normalized)
        if (candidate.exists()) {
            return LocalFileSystem.getInstance().findFileByPath(candidate.canonicalPath)
        }
    }
    return null
}

// Wrap a (file, line, column) triple in a RdSemanticTarget so that backend
// RPCs migrated to RdSemanticTarget can keep accepting position-based requests.
private fun createPositionTarget(filePath: String?, line: Int?, column: Int?): Any? =
    RdProtocolBridge.createStruct("$MODEL_PKG.RdSemanticTarget", filePath, line, column, null, null)

private fun createPositionTarget(project: Project, element: PsiElement): Any? {
    val file = element.containingFile
    val vf = file?.virtualFile
    val filePath = vf?.let { riderBackendPath(it) } ?: ""
    val document = file?.let { PsiDocumentManager.getInstance(project).getDocument(it) }
    val offset = element.textOffset
    val line = document?.getLineNumber(offset)?.plus(1) ?: 1
    val column = document?.let { offset - it.getLineStartOffset(it.getLineNumber(offset)) + 1 } ?: 1
    return createPositionTarget(filePath, line, column)
}

private fun rdSymbolToTypeElementData(project: Project, symbol: Any, language: String): TypeElementData {
    return TypeElementData(
        name = RdProtocolBridge.getProperty(symbol, "name") as? String ?: "",
        qualifiedName = RdProtocolBridge.getProperty(symbol, "qualifiedName") as? String,
        file = (RdProtocolBridge.getProperty(symbol, "filePath") as? String)?.let { displayPath(project, it) },
        line = RdProtocolBridge.getProperty(symbol, "line") as? Int,
        kind = RdProtocolBridge.getProperty(symbol, "kind") as? String ?: "UNKNOWN",
        language = language
    )
}

private fun rdSymbolToImplementationData(project: Project, symbol: Any, language: String): ImplementationData? {
    val rawPath = RdProtocolBridge.getProperty(symbol, "filePath") as? String ?: return null
    return ImplementationData(
        name = RdProtocolBridge.getProperty(symbol, "name") as? String ?: "",
        file = displayPath(project, rawPath),
        line = RdProtocolBridge.getProperty(symbol, "line") as? Int ?: return null,
        column = RdProtocolBridge.getProperty(symbol, "column") as? Int ?: 1,
        kind = (RdProtocolBridge.getProperty(symbol, "kind") as? String ?: "unknown").lowercase(),
        language = language
    )
}

private fun rdSymbolToCallElementData(project: Project, symbol: Any, language: String): CallElementData? {
    val rawPath = RdProtocolBridge.getProperty(symbol, "filePath") as? String ?: return null
    return CallElementData(
        name = RdProtocolBridge.getProperty(symbol, "name") as? String ?: "",
        file = displayPath(project, rawPath),
        line = RdProtocolBridge.getProperty(symbol, "line") as? Int ?: return null,
        column = RdProtocolBridge.getProperty(symbol, "column") as? Int ?: 1,
        language = language
    )
}

private fun displayPath(project: Project, filePath: String?): String {
    if (filePath.isNullOrBlank()) return ""
    return try {
        val normalized = filePath.replace('\\', File.separatorChar).replace('/', File.separatorChar)
        val virtualFile = LocalFileSystem.getInstance().findFileByPath(normalized)
        if (virtualFile != null) ProjectUtils.getToolFilePath(project, virtualFile) else filePath
    } catch (_: Throwable) {
        filePath
    }
}

private fun invokeSemanticCallHierarchy(
    project: Project,
    model: Any,
    target: Any,
    direction: String,
    depth: Int,
    scope: BuiltInSearchScope,
    symbolTarget: Boolean,
    displayLanguage: String = "C#"
): RiderBackendResponse<CallHierarchyData> {
    val shouldBoundCallerExpansion = direction.equals("callers", ignoreCase = true) && depth > 1
    val request = RdProtocolBridge.createStruct(
        "$MODEL_PKG.RdCallHierarchyRequest",
        target,
        direction,
        depth,
        scope.wireValue,
        CALL_HIERARCHY_RESULT_LIMIT
    ) ?: return RiderBackendResponse(
        handled = true,
        errorMessage = symbolTarget.thenUnsupportedCallHierarchy()
    )
    val result = when (val outcome = RdProtocolBridge.invokeCallResult(model, "getCallHierarchy", request)) {
        is RdCallOutcome.Success -> outcome.value
        is RdCallOutcome.Timeout -> {
            return RiderBackendResponse(
                handled = true,
                errorMessage = outcome.toUserMessage("resolving call hierarchy")
            )
        }
        is RdCallOutcome.Failure -> {
            return RiderBackendResponse(
                handled = true,
                errorMessage = outcome.toUserMessage("resolving call hierarchy")
            )
        }
    } ?: return RiderBackendResponse(handled = true)

    val root = RdProtocolBridge.getProperty(result, "root")
        ?.let { rdSymbolToCallElementData(project, it, displayLanguage) }
        ?: return RiderBackendResponse(
            handled = true,
            errorMessage = symbolTarget.thenUnsupportedCallHierarchy()
        )
    @Suppress("UNCHECKED_CAST")
    val calls = (RdProtocolBridge.getProperty(result, "calls") as? List<Any>) ?: emptyList()
    val seen = mutableSetOf<String>()
    val expansionState = RiderCallHierarchyExpansionState()
    val distinctCalls = calls.mapNotNull { rdSymbolToCallElementData(project, it, displayLanguage) }
        .sortedCallElements()
        .filter { seen.add(callHierarchyKey(it)) }
        .take(CALL_HIERARCHY_RESULT_LIMIT)
    val convertedCalls = distinctCalls.mapIndexed { index, call ->
        when {
            depth <= 1 -> call.copy(children = emptyList())
            shouldBoundCallerExpansion && index >= CALL_HIERARCHY_EXPANDED_CHILDREN_PER_NODE_LIMIT -> {
                expansionState.truncated = true
                call.copy(children = emptyList())
            }
            else -> expandSemanticCallHierarchy(project, model, call, direction, depth - 1, scope, seen, displayLanguage, expansionState)
        }
    }
    val message = mergeCallHierarchyMessages(
        RdProtocolBridge.getProperty(result, "message") as? String,
        expansionState.noteOrNull()
    )

    return RiderBackendResponse(
        handled = true,
        value = CallHierarchyData(element = root, calls = convertedCalls),
        message = message
    )
}

private fun expandSemanticCallHierarchy(
    project: Project,
    model: Any,
    call: CallElementData,
    direction: String,
    remainingDepth: Int,
    scope: BuiltInSearchScope,
    seen: MutableSet<String>,
    displayLanguage: String,
    expansionState: RiderCallHierarchyExpansionState
): CallElementData {
    if (remainingDepth <= 0) return call.copy(children = emptyList())

    val target = createPositionTarget(call.file, call.line, call.column)
        ?: return call.copy(children = emptyList())
    val request = RdProtocolBridge.createStruct(
        "$MODEL_PKG.RdCallHierarchyRequest",
        target,
        direction,
        remainingDepth,
        scope.wireValue,
        CALL_HIERARCHY_RESULT_LIMIT
    ) ?: return call.copy(children = emptyList())
    val result = when (val outcome = RdProtocolBridge.invokeCallResult(model, "getCallHierarchy", request)) {
        is RdCallOutcome.Success -> outcome.value
        else -> null
    } ?: return call.copy(children = emptyList())

    @Suppress("UNCHECKED_CAST")
    val children = (RdProtocolBridge.getProperty(result, "calls") as? List<Any>) ?: emptyList()
    val orderedChildren = children.mapNotNull { rdSymbolToCallElementData(project, it, displayLanguage) }
        .sortedCallElements()
        .filter { seen.add(callHierarchyKey(it)) }
        .take(CALL_HIERARCHY_RESULT_LIMIT)
    val convertedChildren = when {
        direction.equals("callers", ignoreCase = true) -> {
            val boundedChildren = boundExpandedCallerChildren(orderedChildren, expansionState)
            if (remainingDepth == 1) {
                boundedChildren.map { it.copy(children = emptyList()) }
            } else {
                boundedChildren.map { child ->
                    expandSemanticCallHierarchy(project, model, child, direction, remainingDepth - 1, scope, seen, displayLanguage, expansionState)
                }
            }
        }
        remainingDepth == 1 -> orderedChildren.map { it.copy(children = emptyList()) }
        else -> orderedChildren.map {
            expandSemanticCallHierarchy(project, model, it, direction, remainingDepth - 1, scope, seen, displayLanguage, expansionState)
        }
    }
    return call.copy(children = convertedChildren)
}

private fun boundExpandedCallerChildren(
    children: List<CallElementData>,
    expansionState: RiderCallHierarchyExpansionState? = null
): List<CallElementData> {
    if (children.size > CALL_HIERARCHY_EXPANDED_CHILDREN_PER_NODE_LIMIT) {
        expansionState?.truncated = true
    }
    return children.take(CALL_HIERARCHY_EXPANDED_CHILDREN_PER_NODE_LIMIT)
}

private data class RiderCallHierarchyExpansionState(
    var truncated: Boolean = false
) {
    fun noteOrNull(): String? =
        if (truncated) {
            "Partial callers expansion: Rider recursively expands only the first $CALL_HIERARCHY_EXPANDED_CHILDREN_PER_NODE_LIMIT children per node to keep backend requests bounded."
        } else {
            null
        }
}

private fun mergeCallHierarchyMessages(primary: String?, secondary: String?): String? = when {
    primary.isNullOrBlank() -> secondary
    secondary.isNullOrBlank() -> primary
    else -> "$primary $secondary"
}

private fun callHierarchyKey(call: CallElementData): String =
    if (call.hasConcreteLocation()) {
        "${call.file}:${call.line}:${call.column}:${call.name}"
    } else {
        "<source-unavailable>:${call.language}:${call.name}"
    }

private fun riderDefinitionMessage(symbolName: String, locationKind: String?, locationDisplayName: String?): String? =
    when (locationKind) {
        "metadata" ->
            "Rider resolved '$symbolName' through metadata. Source is unavailable in this solution; use '${locationDisplayName ?: symbolName}' as the external declaration identity."
        "decompiled" ->
            "Rider resolved '$symbolName' through decompiled code. Treat '${locationDisplayName ?: symbolName}' as a best-available navigation surface, not a project-backed source file."
        "sourceUnavailable" ->
            "Rider resolved '$symbolName', but no source-backed declaration is available in this solution. Use '${locationDisplayName ?: symbolName}' as the external identity or retry with project_and_libraries for broader context."
        else -> null
    }

private fun riderDefinitionPreview(preview: String, message: String?): String =
    preview.ifBlank { message.orEmpty() }

private fun List<UsageLocation>.distinctAndOrderUsageLocations(): List<UsageLocation> =
    this.groupBy(::usageLocationKey)
        .map { (_, group) -> group.minWithOrNull(compareByUsageLocation()) ?: group.first() }
        .sortedWith(compareByUsageLocation())

private fun usageLocationKey(location: UsageLocation): String =
    if (location.hasConcreteLocation()) {
        "${location.file}:${location.line}:${location.column}:${location.type}"
    } else {
        "<source-unavailable>:${location.type}:${location.context}:${location.astPath.joinToString(">")}" 
    }

private fun compareByUsageLocation(): Comparator<UsageLocation> =
    compareBy<UsageLocation>(
        { if (it.hasConcreteLocation()) 0 else 1 },
        { sortableLocationPath(it.file) },
        { if (it.line > 0) it.line else Int.MAX_VALUE },
        { if (it.column > 0) it.column else Int.MAX_VALUE },
        { it.type.lowercase() },
        { it.context.lowercase() },
        { it.astPath.joinToString(">") }
    )

private fun List<CallElementData>.sortedCallElements(): List<CallElementData> =
    sortedWith(compareByCallElement())

private fun compareByCallElement(): Comparator<CallElementData> =
    compareBy<CallElementData>(
        { if (it.hasConcreteLocation()) 0 else 1 },
        { sortableLocationPath(it.file) },
        { if (it.line > 0) it.line else Int.MAX_VALUE },
        { if (it.column > 0) it.column else Int.MAX_VALUE },
        { it.name.lowercase() },
        { it.language.lowercase() }
    )

private fun sortableLocationPath(path: String): String = path.ifBlank { "~" }.lowercase()

private fun UsageLocation.hasConcreteLocation(): Boolean = line > 0 && column > 0

private fun CallElementData.hasConcreteLocation(): Boolean = line > 0 && column > 0

private fun rdStructureKind(kind: String): StructureKind = when (kind.uppercase()) {
    "CLASS", "ABSTRACT_CLASS" -> StructureKind.CLASS
    "INTERFACE" -> StructureKind.INTERFACE
    "STRUCT", "RECORD" -> StructureKind.RECORD
    "ENUM" -> StructureKind.ENUM
    "METHOD" -> StructureKind.METHOD
    "CONSTRUCTOR" -> StructureKind.CONSTRUCTOR
    "PROPERTY" -> StructureKind.PROPERTY
    "FIELD" -> StructureKind.FIELD
    "EVENT" -> StructureKind.PROPERTY
    "DELEGATE" -> StructureKind.CLASS
    "NAMESPACE" -> StructureKind.NAMESPACE
    else -> StructureKind.UNKNOWN
}

/**
 * Rebuilds a tree from a flat depth-annotated list of structure nodes.
 * Uses a two-pass approach since StructureNode is an immutable data class.
 */
private fun rebuildStructureTree(flatNodes: List<Any>): List<StructureNode> {
    if (flatNodes.isEmpty()) return emptyList()

    // First pass: extract flat data
    data class FlatEntry(
        val name: String,
        val kind: String,
        val modifiers: List<String>,
        val signature: String?,
        val line: Int,
        val depth: Int,
        val children: MutableList<FlatEntry> = mutableListOf()
    )

    val entries = flatNodes.map { flat ->
        @Suppress("UNCHECKED_CAST")
        FlatEntry(
            name = RdProtocolBridge.getProperty(flat, "name") as? String ?: "",
            kind = RdProtocolBridge.getProperty(flat, "kind") as? String ?: "UNKNOWN",
            modifiers = (RdProtocolBridge.getProperty(flat, "modifiers") as? List<String>) ?: emptyList(),
            signature = RdProtocolBridge.getProperty(flat, "signature") as? String,
            line = RdProtocolBridge.getProperty(flat, "line") as? Int ?: 1,
            depth = RdProtocolBridge.getProperty(flat, "depth") as? Int ?: 0
        )
    }

    // Second pass: build parent-child relationships
    val stack = mutableListOf<FlatEntry>()
    val roots = mutableListOf<FlatEntry>()

    for (entry in entries) {
        while (stack.isNotEmpty() && stack.last().depth >= entry.depth) {
            stack.removeLast()
        }
        if (stack.isEmpty()) {
            roots.add(entry)
        } else {
            stack.last().children.add(entry)
        }
        stack.add(entry)
    }

    // Third pass: convert to immutable StructureNode tree
    fun toStructureNode(entry: FlatEntry): StructureNode = StructureNode(
        name = entry.name,
        kind = rdStructureKind(entry.kind),
        modifiers = entry.modifiers,
        signature = entry.signature,
        line = entry.line,
        children = entry.children.map { toStructureNode(it) }
    )

    return roots.map { toStructureNode(it) }
}

// ── Abstract base for protocol-based handlers ───────────────────────────────

abstract class BaseRiderHandler<T>(
    final override val languageId: String,
    protected val displayLanguage: String,
    private val supportedExtensions: Set<String>,
    private val supportedLanguageIds: Set<String>,
) : LanguageHandler<T> {

    override fun isAvailable(): Boolean = RiderEnvironment.isAvailable

    override fun canHandle(element: PsiElement): Boolean =
        isAvailable() && isDotNetElement(element, supportedExtensions, supportedLanguageIds)
}

// ── Type Hierarchy Handlers ─────────────────────────────────────────────────

abstract class RiderTypeHierarchyHandler(
    languageId: String,
    displayLanguage: String,
    supportedExtensions: Set<String>,
    supportedLanguageIds: Set<String>,
) : BaseRiderHandler<TypeHierarchyData>(languageId, displayLanguage, supportedExtensions, supportedLanguageIds),
    TypeHierarchyHandler {

    override fun getTypeHierarchy(element: PsiElement, project: Project, scope: BuiltInSearchScope): TypeHierarchyData? {
        val position = createSourcePosition(project, element) ?: return null
        val result = RiderBackendSemanticService.run {
            val hierarchyResult = invokeTypeHierarchy(project, position, scope) ?: return null
            rdTypeHierarchyToData(project, hierarchyResult, displayLanguage)
        }
        return result
    }
}

// ── Implementations Handlers ────────────────────────────────────────────────

abstract class RiderImplementationsHandler(
    languageId: String,
    displayLanguage: String,
    supportedExtensions: Set<String>,
    supportedLanguageIds: Set<String>,
) : BaseRiderHandler<List<ImplementationData>>(languageId, displayLanguage, supportedExtensions, supportedLanguageIds),
    ImplementationsHandler {

    override fun findImplementations(element: PsiElement, project: Project, scope: BuiltInSearchScope): List<ImplementationData>? {
        val model = RdProtocolBridge.getModel(project) ?: return null
        val position = createSourcePosition(project, element) ?: return null
        val request = RdProtocolBridge.createStruct(
            "$MODEL_PKG.RdImplementationsRequest",
            position,
            scope.wireValue,
            IMPLEMENTATIONS_RESULT_LIMIT
        ) ?: return null
        val result = RdProtocolBridge.invokeCall(model, "findImplementations", request) ?: return null

        @Suppress("UNCHECKED_CAST")
        val implementations = (RdProtocolBridge.getProperty(result, "implementations") as? List<Any>) ?: emptyList()
        val directResults = implementations.mapNotNull { rdSymbolToImplementationData(project, it, displayLanguage) }
        if (directResults.isNotEmpty()) return directResults

        val hierarchyRequest = RdProtocolBridge.createStruct("$MODEL_PKG.RdTypeHierarchyRequest", position, scope.wireValue) ?: return directResults
        val hierarchyResult = RdProtocolBridge.invokeCall(model, "getTypeHierarchy", hierarchyRequest) ?: return directResults
        @Suppress("UNCHECKED_CAST")
        val subtypes = (RdProtocolBridge.getProperty(hierarchyResult, "subtypes") as? List<Any>) ?: emptyList()
        val subtypeResults = subtypes.mapNotNull { rdSymbolToImplementationData(project, it, displayLanguage) }
        return subtypeResults
    }
}

// ── Call Hierarchy Handlers ─────────────────────────────────────────────────

abstract class RiderCallHierarchyHandler(
    languageId: String,
    displayLanguage: String,
    supportedExtensions: Set<String>,
    supportedLanguageIds: Set<String>,
) : BaseRiderHandler<CallHierarchyData>(languageId, displayLanguage, supportedExtensions, supportedLanguageIds),
    CallHierarchyHandler {

    override fun getCallHierarchy(
        element: PsiElement,
        project: Project,
        direction: String,
        depth: Int,
        scope: BuiltInSearchScope
    ): CallHierarchyData? {
        val model = RdProtocolBridge.getModel(project) ?: return null
        val target = createPositionTarget(project, element) ?: return null
        val request = RdProtocolBridge.createStruct(
            "$MODEL_PKG.RdCallHierarchyRequest",
            target,
            direction,
            depth,
            scope.wireValue,
            CALL_HIERARCHY_RESULT_LIMIT
        ) ?: return null
        val result = invokeCallHierarchy(model, request) ?: return null

        val root = RdProtocolBridge.getProperty(result, "root") ?: return null
        @Suppress("UNCHECKED_CAST")
        val calls = (RdProtocolBridge.getProperty(result, "calls") as? List<Any>) ?: emptyList()
        // Single seen set shared across the whole tree so that sibling subtrees do not
        // re-expand callees they have collectively already visited. Without this dedup,
        // wide call graphs trigger exponential backend round-trips (root cause of the
        // historical "deep call hierarchy is slow" symptom).
        val seen = mutableSetOf<String>()
        val convertedCalls = calls.mapNotNull { rdSymbolToCallElementData(project, it, displayLanguage) }
            .filter { seen.add(callKey(it)) }
            .take(CALL_HIERARCHY_RESULT_LIMIT)
            .map { call ->
                when {
                    depth <= 1 -> call.copy(children = emptyList())
                    else -> expandCallHierarchy(project, call, direction, depth - 1, scope, seen)
                }
            }

        return CallHierarchyData(
            element = rdSymbolToCallElementData(project, root, displayLanguage) ?: return null,
            calls = convertedCalls
        )
    }

    private fun expandCallHierarchy(
        project: Project,
        call: CallElementData,
        direction: String,
        remainingDepth: Int,
        scope: BuiltInSearchScope,
        seen: MutableSet<String>
    ): CallElementData {
        if (remainingDepth <= 0) return call.copy(children = emptyList())
        val target = createPositionTarget(call.file, call.line, call.column)
            ?: return call.copy(children = emptyList())
        val request = RdProtocolBridge.createStruct(
            "$MODEL_PKG.RdCallHierarchyRequest",
            target,
            direction,
            remainingDepth,
            scope.wireValue,
            CALL_HIERARCHY_RESULT_LIMIT
        ) ?: return call.copy(children = emptyList())
        val model = RdProtocolBridge.getModel(project) ?: return call.copy(children = emptyList())
        val result = invokeCallHierarchy(model, request) ?: return call.copy(children = emptyList())
        @Suppress("UNCHECKED_CAST")
        val children = (RdProtocolBridge.getProperty(result, "calls") as? List<Any>) ?: emptyList()
        val orderedChildren = children.mapNotNull { rdSymbolToCallElementData(project, it, displayLanguage) }
            .filter { seen.add(callKey(it)) }
            .take(CALL_HIERARCHY_RESULT_LIMIT)
        val convertedChildren = when {
            direction.equals("callers", ignoreCase = true) -> {
                if (remainingDepth == 1) {
                    orderedChildren.map { it.copy(children = emptyList()) }
                } else {
                    orderedChildren.map { child -> expandCallHierarchy(project, child, direction, remainingDepth - 1, scope, seen) }
                }
            }
            remainingDepth == 1 -> orderedChildren.map { it.copy(children = emptyList()) }
            else -> orderedChildren.map { child -> expandCallHierarchy(project, child, direction, remainingDepth - 1, scope, seen) }
        }
        return call.copy(children = convertedChildren)
    }

    private fun invokeCallHierarchy(model: Any, request: Any): Any? =
        when (val outcome = RdProtocolBridge.invokeCallResult(model, "getCallHierarchy", request)) {
            is RdCallOutcome.Success -> outcome.value
            is RdCallOutcome.Timeout -> throw RiderBackendTimeoutException(
                callName = outcome.callName,
                timeoutSeconds = outcome.timeoutSeconds,
                operation = "resolving call hierarchy"
            )
            is RdCallOutcome.Failure -> null
        }

    private fun callKey(call: CallElementData): String =
        "${call.file}:${call.line}:${call.column}:${call.name}"

    private companion object {
        // Mirrors JavaCallHierarchyHandler.MAX_RESULTS_PER_LEVEL to keep behaviour consistent
        // across IDEs and to bound RD round-trips for fan-out methods.
    }
}

// ── Symbol Reference Handlers ────────────────────────────────────────────────

internal data class ParsedRiderSymbol(
    val languageName: String,
    val containerQualifiedName: String,
    val memberName: String?,
    val parameterTypes: List<String>?,
    val isConstructor: Boolean,
    val normalizedSymbol: String
)

internal object RiderSymbolParser {
    private val BUILT_IN_TYPE_ALIASES = mapOf(
        "bool" to "System.Boolean",
        "byte" to "System.Byte",
        "sbyte" to "System.SByte",
        "short" to "System.Int16",
        "ushort" to "System.UInt16",
        "int" to "System.Int32",
        "uint" to "System.UInt32",
        "long" to "System.Int64",
        "ulong" to "System.UInt64",
        "float" to "System.Single",
        "double" to "System.Double",
        "decimal" to "System.Decimal",
        "char" to "System.Char",
        "string" to "System.String",
        "object" to "System.Object",
        "nativeint" to "System.IntPtr",
        "unativeint" to "System.UIntPtr"
    )

    fun parse(languageName: String, symbol: String): Result<ParsedRiderSymbol> {
        val trimmed = symbol.trim()
        if (trimmed.isEmpty()) return invalidFormat(symbol, languageName)

        val separatorIndex = trimmed.indexOf('#')
        if (separatorIndex >= 0 && trimmed.indexOf('#', separatorIndex + 1) >= 0) {
            return invalidFormat(symbol, languageName)
        }

        if (separatorIndex < 0) {
            if ('(' in trimmed || ')' in trimmed) return invalidFormat(symbol, languageName)
            val normalizedContainer = normalizeQualifiedName(trimmed)
            if (normalizedContainer.isBlank()) return invalidFormat(symbol, languageName)
            return Result.success(ParsedRiderSymbol(languageName, normalizedContainer, null, null, false, normalizedContainer))
        }

        val rawContainer = trimmed.substring(0, separatorIndex)
        val rawMemberPart = trimmed.substring(separatorIndex + 1)
        if (rawContainer.isBlank() || rawMemberPart.isBlank()) return invalidFormat(symbol, languageName)

        val normalizedContainer = normalizeQualifiedName(rawContainer)
        if (normalizedContainer.isBlank()) return invalidFormat(symbol, languageName)
        val parsedMember = parseMemberPart(normalizedContainer, rawMemberPart) ?: return invalidFormat(symbol, languageName)
        val normalizedSymbol = buildNormalizedSymbol(normalizedContainer, parsedMember)
        return Result.success(
            ParsedRiderSymbol(
                languageName = languageName,
                containerQualifiedName = normalizedContainer,
                memberName = parsedMember.memberName,
                parameterTypes = parsedMember.parameterTypes,
                isConstructor = parsedMember.isConstructor,
                normalizedSymbol = normalizedSymbol
            )
        )
    }

    internal fun callHierarchyCallableGuidance(languageName: String, symbol: String): String? {
        val parsed = parse(languageName, symbol).getOrElse { return it.message ?: "Invalid Rider symbol format." }
        if (parsed.memberName != null) return null

        val normalizedSymbol = symbol.trim()
        val dottedCallableSuggestion = suggestCallableHashSyntax(normalizedSymbol)
        return if (dottedCallableSuggestion != null) {
            "Rider $languageName call hierarchy needs a callable symbol. '$normalizedSymbol' looks like dotted member syntax; use '$dottedCallableSuggestion' instead."
        } else {
            val examples = symbolExamples(languageName).drop(1).joinToString(" or ")
            "Rider $languageName call hierarchy needs a callable symbol. Use $examples."
        }
    }

    private data class ParsedMember(val memberName: String, val parameterTypes: List<String>?, val isConstructor: Boolean)

    private fun parseMemberPart(containerPart: String, memberPart: String): ParsedMember? {
        val openParenIndex = memberPart.indexOf('(')
        val memberName: String
        val parameterTypes: List<String>?
        if (openParenIndex < 0) {
            memberName = memberPart.trim()
            parameterTypes = null
        } else {
            val closeParenIndex = memberPart.lastIndexOf(')')
            if (closeParenIndex != memberPart.length - 1 || closeParenIndex < openParenIndex) return null
            memberName = memberPart.substring(0, openParenIndex).trim()
            parameterTypes = parseParameterList(memberPart.substring(openParenIndex + 1, closeParenIndex)) ?: return null
        }
        if (memberName.isBlank()) return null

        val normalizedMemberName = normalizeSimpleName(memberName)
        val normalizedContainerLeaf = normalizeSimpleName(getContainerLeafName(containerPart))
        val isConstructor = normalizedMemberName.equals(".ctor", ignoreCase = true) ||
            normalizedMemberName.equals(normalizedContainerLeaf, ignoreCase = true)
        return ParsedMember(if (isConstructor) ".ctor" else normalizedMemberName, parameterTypes, isConstructor)
    }

    private fun parseParameterList(rawParameters: String): List<String>? {
        if (rawParameters.isBlank()) return emptyList()
        val parts = mutableListOf<String>()
        var start = 0
        var angleDepth = 0
        var bracketDepth = 0
        for (i in rawParameters.indices) {
            when (rawParameters[i]) {
                '<' -> angleDepth++
                '>' -> angleDepth--
                '[' -> bracketDepth++
                ']' -> bracketDepth--
                ',' -> if (angleDepth == 0 && bracketDepth == 0) {
                    val segment = rawParameters.substring(start, i).trim()
                    if (segment.isBlank()) return null
                    parts += canonicalizeTypeName(segment)
                    start = i + 1
                }
            }
            if (angleDepth < 0 || bracketDepth < 0) return null
        }
        if (angleDepth != 0 || bracketDepth != 0) return null
        val lastSegment = rawParameters.substring(start).trim()
        if (lastSegment.isBlank()) return null
        parts += canonicalizeTypeName(lastSegment)
        return parts
    }

    private fun buildNormalizedSymbol(containerPart: String, member: ParsedMember): String = when (member.parameterTypes) {
        null -> "$containerPart#${member.memberName}"
        else -> "$containerPart#${member.memberName}(${member.parameterTypes.joinToString(",")})"
    }

    private fun invalidFormat(symbol: String, languageName: String): Result<ParsedRiderSymbol> =
        ErrorMessages.invalidSymbolFormat(symbol, symbolExamples(languageName)).toArgumentFailure()

    private fun symbolExamples(languageName: String): List<String> {
        @Suppress("UNUSED_PARAMETER") val unused = languageName
        return listOf(
            "'Namespace.Type'",
            "'Namespace.Type#MemberName'",
            "'Namespace.Type#MethodName(string, int[])'"
        )
    }

    private fun getContainerLeafName(containerQualifiedName: String): String {
        val normalized = normalizeQualifiedName(containerQualifiedName)
        val separatorIndex = maxOf(normalized.lastIndexOf('.'), normalized.lastIndexOf('+'))
        return if (separatorIndex >= 0) normalized.substring(separatorIndex + 1) else normalized
    }

    private fun normalizeQualifiedName(value: String): String {
        val withoutGlobalPrefix = value.trim()
            .replace("global::", "", ignoreCase = true)
            .replace("global.", "", ignoreCase = true)
        return canonicalizeTypeName(withoutGlobalPrefix)
    }

    private fun canonicalizeTypeName(value: String): String {
        val normalized = normalizeSimpleName(value).replace("+", ".")
        return BUILT_IN_TYPE_ALIASES.entries.firstOrNull { it.key.equals(normalized, ignoreCase = true) }?.value ?: normalized
    }

    private fun normalizeSimpleName(value: String): String {
        val normalized = removeGenericPayload(value)
            .replace("::", ".")
            .replace(" ", "")
            .trim()
        return normalized.replace(Regex("`\\d+"), "")
    }

    private fun removeGenericPayload(value: String): String {
        if (value.isEmpty()) return ""
        val result = StringBuilder(value.length)
        var depth = 0
        for (ch in value) {
            when (ch) {
                '<' -> depth++
                '>' -> if (depth > 0) depth--
                else -> if (depth == 0) result.append(ch)
            }
        }
        return result.toString()
    }

    private fun suggestCallableHashSyntax(symbol: String): String? {
        if ('#' in symbol || '(' in symbol || ')' in symbol) return null
        val normalized = normalizeQualifiedName(symbol)
        if (normalized.count { it == '.' } < 2) return null
        val separatorIndex = normalized.lastIndexOf('.')
        if (separatorIndex <= 0 || separatorIndex == normalized.lastIndex) return null
        val container = normalized.substring(0, separatorIndex)
        val member = normalized.substring(separatorIndex + 1)
        if (member.isBlank()) return null
        return "$container#$member"
    }
}

abstract class BaseRiderSymbolReferenceHandler(
    languageId: String,
    private val displayName: String,
    supportedExtensions: Set<String>,
    supportedLanguageIds: Set<String>,
) : BaseRiderHandler<PsiNamedElement>(languageId, displayName, supportedExtensions, supportedLanguageIds), SymbolReferenceHandler {

    override val languageName: String = displayName

    override fun resolveSymbol(project: Project, symbol: String): Result<PsiNamedElement> {
        val parsed = RiderSymbolParser.parse(displayName, symbol).getOrElse { return Result.failure(it) }
        val resolution = RiderBackendSemanticService.resolveIndexedSymbol(project, displayName, parsed.normalizedSymbol)
            ?: return Result.failure(IllegalArgumentException(ErrorMessages.COULD_NOT_RESOLVE_SYMBOL))

        if (!resolution.status.equals("success", ignoreCase = true)) {
            return Result.failure(
                IllegalArgumentException(
                    resolution.message ?: "Could not resolve Rider symbol '${parsed.normalizedSymbol}' (${resolution.status})."
                )
            )
        }

        val symbolInfo = resolution.symbolInfo
            ?: return Result.failure(IllegalArgumentException(ErrorMessages.COULD_NOT_RESOLVE_SYMBOL))
        val filePath = RdProtocolBridge.getProperty(symbolInfo, "filePath") as? String
        val line = RdProtocolBridge.getProperty(symbolInfo, "line") as? Int
        val column = RdProtocolBridge.getProperty(symbolInfo, "column") as? Int
        if (filePath.isNullOrBlank() || line == null || column == null) {
            return Result.failure(IllegalArgumentException(ErrorMessages.COULD_NOT_RESOLVE_SYMBOL))
        }

        val target = findNamedElementAtPosition(project, filePath, line, column)
            ?: return Result.failure(IllegalArgumentException(ErrorMessages.COULD_NOT_RESOLVE_SYMBOL))
        return Result.success(target)
    }
}

// ── Super Methods Handlers ──────────────────────────────────────────────────

abstract class RiderSuperMethodsHandler(
    languageId: String,
    displayLanguage: String,
    supportedExtensions: Set<String>,
    supportedLanguageIds: Set<String>,
) : BaseRiderHandler<SuperMethodsData>(languageId, displayLanguage, supportedExtensions, supportedLanguageIds),
    SuperMethodsHandler {

    override fun findSuperMethods(element: PsiElement, project: Project): SuperMethodsData? {
        val model = RdProtocolBridge.getModel(project) ?: return null
        val position = createSourcePosition(project, element) ?: return null
        val request = RdProtocolBridge.createStruct("$MODEL_PKG.RdSuperMethodsRequest", position) ?: return null
        val result = RdProtocolBridge.invokeCall(model, "findSuperMethods", request) ?: return null

        val method = RdProtocolBridge.getProperty(result, "method") ?: return null
        @Suppress("UNCHECKED_CAST")
        val hierarchy = (RdProtocolBridge.getProperty(result, "hierarchy") as? List<Any>) ?: emptyList()

        fun usableName(value: String?): String =
            value?.takeUnless { it.isBlank() } ?: "unknown"
        val methodName = usableName(RdProtocolBridge.getProperty(method, "name") as? String)

        return SuperMethodsData(
            method = MethodData(
                name = methodName,
                signature = (RdProtocolBridge.getProperty(method, "signature") as? String)
                    ?.takeUnless { it.isBlank() || it.equals("unknown", ignoreCase = true) } ?: methodName,
                containingClass = (RdProtocolBridge.getProperty(method, "qualifiedName") as? String)
                    ?.substringBeforeLast('.', "unknown") ?: "unknown",
                file = displayPath(project, RdProtocolBridge.getProperty(method, "filePath") as? String)
                    .takeUnless { it.isEmpty() } ?: return null,
                line = RdProtocolBridge.getProperty(method, "line") as? Int ?: return null,
                column = RdProtocolBridge.getProperty(method, "column") as? Int ?: 1,
                language = displayLanguage
            ),
            hierarchy = hierarchy.map { superInfo ->
                val symbol = RdProtocolBridge.getProperty(superInfo, "symbol")
                val superName = usableName(symbol?.let { RdProtocolBridge.getProperty(it, "name") as? String })
                SuperMethodData(
                    name = superName,
                    signature = (symbol?.let { RdProtocolBridge.getProperty(it, "signature") as? String })
                        ?.takeUnless { it.isBlank() || it.equals("unknown", ignoreCase = true) } ?: superName,
                    containingClass = RdProtocolBridge.getProperty(superInfo, "containingTypeName") as? String ?: "",
                    containingClassKind = RdProtocolBridge.getProperty(superInfo, "containingTypeKind") as? String ?: "CLASS",
                    file = symbol?.let { displayPath(project, RdProtocolBridge.getProperty(it, "filePath") as? String) }
                        ?.takeUnless { it.isEmpty() },
                    line = symbol?.let { RdProtocolBridge.getProperty(it, "line") as? Int },
                    column = symbol?.let { RdProtocolBridge.getProperty(it, "column") as? Int },
                    isInterface = RdProtocolBridge.getProperty(superInfo, "isInterface") as? Boolean ?: false,
                    depth = RdProtocolBridge.getProperty(superInfo, "depth") as? Int ?: 0,
                    language = displayLanguage
                )
            }
        )
    }
}

// ── Structure Handlers ──────────────────────────────────────────────────────

abstract class RiderStructureHandler(
    languageId: String,
    displayLanguage: String,
    supportedExtensions: Set<String>,
    supportedLanguageIds: Set<String>,
) : BaseRiderHandler<List<StructureNode>>(languageId, displayLanguage, supportedExtensions, supportedLanguageIds),
    StructureHandler {

    override fun getFileStructure(file: PsiFile, project: Project): List<StructureNode> {
        val model = RdProtocolBridge.getModel(project) ?: return emptyList()
        val filePath = file.virtualFile?.let { riderBackendPath(it) } ?: return emptyList()
        val request = RdProtocolBridge.createStruct("$MODEL_PKG.RdFileStructureRequest", filePath) ?: return emptyList()
        val result = RdProtocolBridge.invokeCall(model, "getFileStructure", request) ?: return emptyList()

        @Suppress("UNCHECKED_CAST")
        val nodes = (RdProtocolBridge.getProperty(result, "nodes") as? List<Any>) ?: emptyList()
        return rebuildStructureTree(nodes)
    }
}

// ── Concrete C# Handlers ────────────────────────────────────────────────────

class RiderCSharpTypeHierarchyHandler : RiderTypeHierarchyHandler("C#", "C#", CSHARP_EXTENSIONS, CSHARP_LANGUAGE_IDS)
class RiderCSharpImplementationsHandler : RiderImplementationsHandler("C#", "C#", CSHARP_EXTENSIONS, CSHARP_LANGUAGE_IDS)
class RiderCSharpCallHierarchyHandler : RiderCallHierarchyHandler("C#", "C#", CSHARP_EXTENSIONS, CSHARP_LANGUAGE_IDS)
class RiderCSharpSuperMethodsHandler : RiderSuperMethodsHandler("C#", "C#", CSHARP_EXTENSIONS, CSHARP_LANGUAGE_IDS)
class RiderCSharpSymbolReferenceHandler : BaseRiderSymbolReferenceHandler("C#", "C#", CSHARP_EXTENSIONS, CSHARP_LANGUAGE_IDS)
class RiderCSharpStructureHandler : RiderStructureHandler("C#", "C#", CSHARP_EXTENSIONS, CSHARP_LANGUAGE_IDS)
