package com.github.hechtcarmel.jetbrainsindexmcpplugin.handlers.dotnet

import com.github.hechtcarmel.jetbrainsindexmcpplugin.handlers.*
import com.github.hechtcarmel.jetbrainsindexmcpplugin.tools.models.StructureKind
import com.github.hechtcarmel.jetbrainsindexmcpplugin.tools.models.StructureNode
import com.github.hechtcarmel.jetbrainsindexmcpplugin.tools.models.DefinitionResult
import com.github.hechtcarmel.jetbrainsindexmcpplugin.tools.models.SymbolMatch
import com.github.hechtcarmel.jetbrainsindexmcpplugin.tools.models.UsageLocation
import com.github.hechtcarmel.jetbrainsindexmcpplugin.util.ProjectUtils
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.diagnostic.logger
import com.intellij.openapi.vfs.LocalFileSystem
import com.intellij.openapi.project.Project
import com.intellij.openapi.vfs.VirtualFile
import com.intellij.psi.PsiDocumentManager
import com.intellij.psi.PsiElement
import com.intellij.psi.PsiFile
import java.io.File
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit

/**
 * Rider protocol-based handlers for C# and F# code intelligence.
 *
 * These handlers delegate to the ReSharper backend via the rd protocol model,
 * providing full semantic analysis instead of the heuristic-based approach.
 * They are only registered when running inside Rider.
 *
 * All access to the rd protocol model uses reflection because the generated
 * protocol stubs are only available in Rider's runtime classpath, not during
 * compilation against IntelliJ Community (IC).
 */
object RiderDotNetHandlers {
    private val LOG = logger<RiderDotNetHandlers>()

    @JvmStatic
    fun register(registry: LanguageHandlerRegistry) {
        if (!isRiderEnvironment()) {
            LOG.info("Not running in Rider, skipping Rider protocol handler registration")
            return
        }
        if (!isRiderProtocolGenerated()) {
            LOG.warn(
                "Rider Index MCP protocol stubs are not available. " +
                    "Skipping C#/F# semantic handlers instead of falling back to frontend PSI heuristics."
            )
            return
        }

        // C# handlers
        registry.registerTypeHierarchyHandler(RiderCSharpTypeHierarchyHandler())
        registry.registerImplementationsHandler(RiderCSharpImplementationsHandler())
        registry.registerCallHierarchyHandler(RiderCSharpCallHierarchyHandler())
        registry.registerSuperMethodsHandler(RiderCSharpSuperMethodsHandler())
        registry.registerStructureHandler(RiderCSharpStructureHandler())

        // F# handlers
        registry.registerTypeHierarchyHandler(RiderFSharpTypeHierarchyHandler())
        registry.registerImplementationsHandler(RiderFSharpImplementationsHandler())
        registry.registerCallHierarchyHandler(RiderFSharpCallHierarchyHandler())
        registry.registerSuperMethodsHandler(RiderFSharpSuperMethodsHandler())
        registry.registerStructureHandler(RiderFSharpStructureHandler())

        LOG.info("Registered Rider protocol-based .NET handlers for C# and F#")
    }

    private fun isRiderEnvironment(): Boolean = RiderEnvironment.isAvailable

    private fun isRiderProtocolGenerated(): Boolean = RiderEnvironment.isProtocolGenerated
}

/**
 * Cached Rider environment + protocol-stub detection. The lookups are reflection-based and
 * never change for the lifetime of the JVM, so we resolve them once via `lazy { }`.
 *
 * Using `lazy` (not eager init) avoids ordering hazards if Rider classes load late.
 */
internal object RiderEnvironment {
    val isAvailable: Boolean by lazy {
        try {
            Class.forName("com.jetbrains.rider.projectView.solution.SolutionLifecycleHost")
            true
        } catch (_: ClassNotFoundException) {
            try {
                Class.forName("com.jetbrains.rider.projectView.SolutionLifecycleHost")
                true
            } catch (_: ClassNotFoundException) {
                false
            }
        }
    }

    val isProtocolGenerated: Boolean by lazy {
        try {
            Class.forName("$MODEL_PKG.IndexMcpModel")
            Class.forName("$MODEL_PKG.IndexMcpModel_GeneratedKt")
            true
        } catch (_: ClassNotFoundException) {
            false
        }
    }
}

// ── Reflection-based rd protocol access ─────────────────────────────────────

/**
 * Wraps reflection calls to the rd protocol model.
 *
 * The IndexMcpModel extension property on IProtocol is generated by rdgen and
 * is only available at runtime inside Rider. We access it reflectively so the
 * plugin can compile against IC.
 */
object RdProtocolBridge {
    private val LOG = logger<RdProtocolBridge>()

    // Reflection caches. Keys are class-name + member signature; values are immutable per JVM lifetime.
    // ConcurrentHashMap.computeIfAbsent is safe — Method/Constructor lookups are pure functions.
    private val methodCache = java.util.concurrent.ConcurrentHashMap<String, java.lang.reflect.Method>()
    private val constructorCache = java.util.concurrent.ConcurrentHashMap<String, java.lang.reflect.Constructor<*>?>()

    private fun cachedMethod(clazz: Class<*>, name: String, vararg paramTypes: Class<*>): java.lang.reflect.Method {
        val key = "${clazz.name}#$name(${paramTypes.joinToString(",") { it.name }})"
        return methodCache.computeIfAbsent(key) { clazz.getMethod(name, *paramTypes) }
    }

    private fun cachedConstructor(clazz: Class<*>, arity: Int): java.lang.reflect.Constructor<*>? {
        val key = "${clazz.name}#<init>($arity)"
        return constructorCache.computeIfAbsent(key) {
            clazz.constructors.firstOrNull { it.parameterCount == arity }
        }
    }

    /**
     * Gets the IndexMcpModel from a Project's Rider protocol host.
     * Returns null if Rider classes aren't available.
     */
    fun getModel(project: Project): Any? {
        getModelFromProtocolListener(project)?.let { return it }
        getModelFromSolution(project)?.let { return it }
        return try {
            // ProtocolManager.getOrCreate(project).protocol.indexMcpModel → IndexMcpModel
            val protocol = getProtocol(project) ?: return null
            val protocolClass = Class.forName("com.jetbrains.rd.framework.IProtocol")
            val modelExtClass = Class.forName("com.jetbrains.rd.ide.model.IndexMcpModel_GeneratedKt")
            val getModel = modelExtClass.getMethod("getIndexMcpModel", protocolClass)
            getModel.invoke(null, protocol)
        } catch (e: Exception) {
            LOG.warn("Failed to get IndexMcpModel via reflection: ${e.message}")
            null
        }
    }

    private fun getModelFromSolution(project: Project): Any? {
        return try {
            val solutionHostExtensions = Class.forName("com.jetbrains.rider.projectView.SolutionHostExtensionsKt")
            val solution = solutionHostExtensions.getMethod("getSolution", Project::class.java).invoke(null, project)
                ?: return null
            val solutionClass = Class.forName("com.jetbrains.rd.ide.model.Solution")
            val modelExtClass = Class.forName("com.jetbrains.rd.ide.model.IndexMcpModel_GeneratedKt")
            val getModel = modelExtClass.getMethod("getIndexMcpModel", solutionClass)
            getModel.invoke(null, solution)
        } catch (e: Exception) {
            LOG.debug("Failed to get solution-scoped IndexMcpModel via reflection: ${e.message}")
            null
        }
    }

    private fun getModelFromProtocolListener(project: Project): Any? {
        return try {
            val storeClass = Class.forName("com.jetbrains.rider.plugins.indexmcp.IndexMcpProtocolModelStore")
            val get = storeClass.getMethod("get", Project::class.java)
            get.invoke(null, project)
        } catch (e: Exception) {
            LOG.debug("IndexMcpProtocolModelStore is not available: ${e.message}")
            null
        }
    }

    private fun getProtocol(project: Project): Any? {
        val protocolManagerClass = Class.forName("com.jetbrains.rider.protocol.ProtocolManager")
        val protocolManager = ApplicationManager.getApplication().getService(protocolManagerClass) ?: return null
        val getOrCreate = protocolManagerClass.getMethod("getOrCreate", Project::class.java)
        val protocolHost = getOrCreate.invoke(protocolManager, project) ?: return null
        return protocolHost.javaClass.getMethod("getProtocol").invoke(protocolHost)
    }

    /**
     * Invokes a named RdCall on the model synchronously.
     *
     * @param model The IndexMcpModel instance
     * @param callName The RPC method name (e.g., "getTypeHierarchy")
     * @param request The request object (an rd structdef instance)
     * @return The response object, or null
     */
    fun invokeCall(model: Any, callName: String, request: Any): Any? {
        return try {
            val callField = cachedMethod(model.javaClass, "get${callName.replaceFirstChar { it.uppercaseChar() }}")
            val rdCall = callField.invoke(model)
            val protocol = cachedMethod(model.javaClass, "getProtocol").invoke(model)
            var lifetime = cachedMethod(protocol.javaClass, "getLifetime").invoke(protocol)
            val lifetimeClass = Class.forName("com.jetbrains.rd.util.lifetime.Lifetime")
            if (!lifetimeClass.isInstance(lifetime)) {
                lifetime = cachedMethod(lifetime.javaClass, "getLifetime").invoke(lifetime)
            }
            val scheduler = cachedMethod(protocol.javaClass, "getScheduler").invoke(protocol)
            val resultLatch = CountDownLatch(1)
            var taskResult: Any? = null
            var failure: Throwable? = null
            val startRequest: () -> Unit = {
                try {
                    val startMethod = cachedMethod(rdCall.javaClass, "start", Any::class.java)
                    val rdTask = startMethod.invoke(rdCall, request)
                    val resultView = cachedMethod(rdTask.javaClass, "getResult").invoke(rdTask)
                    taskResult = cachedMethod(resultView.javaClass, "getValueOrNull").invoke(resultView)
                    if (taskResult == null) {
                        val callback: (Any?) -> Unit = {
                            taskResult = it
                            resultLatch.countDown()
                        }
                        cachedMethod(resultView.javaClass, "advise", lifetimeClass, kotlin.jvm.functions.Function1::class.java)
                            .invoke(resultView, lifetime, callback)
                    } else {
                        resultLatch.countDown()
                    }
                } catch (e: Throwable) {
                    failure = e
                    resultLatch.countDown()
                }
            }
            val isActive = cachedMethod(scheduler.javaClass, "isActive").invoke(scheduler) as Boolean
            if (isActive) {
                startRequest()
            } else {
                cachedMethod(scheduler.javaClass, "queue", kotlin.jvm.functions.Function0::class.java)
                    .invoke(scheduler, startRequest)
            }
            val timeoutSeconds = rdCallTimeoutSeconds(callName)
            if (!resultLatch.await(timeoutSeconds, TimeUnit.SECONDS)) {
                throw IllegalStateException("Timed out waiting for Rider backend rd call '$callName'")
            }
            failure?.let { throw it }
            unwrapRdTaskResult(taskResult)
        } catch (e: Exception) {
            val cause = (e as? java.lang.reflect.InvocationTargetException)?.targetException ?: e.cause ?: e
            LOG.warn("Failed to invoke rd call '$callName': ${cause::class.java.simpleName}: ${cause.message}")
            null
        }
    }

    private fun rdCallTimeoutSeconds(callName: String): Long = when (callName) {
        "renameSymbol", "getCallHierarchy" -> 300L
        else -> 60L
    }

    private fun unwrapRdTaskResult(taskResult: Any?): Any? {
        if (taskResult == null) {
            return null
        }
        return when (taskResult.javaClass.simpleName) {
            "Success" -> taskResult.javaClass.getMethod("getValue").invoke(taskResult)
            "Fault" -> {
                val error = taskResult.javaClass.getMethod("getError").invoke(taskResult)
                throw IllegalStateException(error.toString())
            }
            "Cancelled" -> throw IllegalStateException("Rider backend rd call was cancelled")
            else -> throw IllegalStateException("Unexpected Rider backend rd task result: ${taskResult.javaClass.name}")
        }
    }

    /**
     * Creates an rd struct instance via its constructor reflectively.
     *
     * Returns null when no constructor matches the supplied arity. Previous behaviour fell back to
     * `clazz.constructors.first()` on no match, which would invoke an arbitrary constructor with
     * mismatched arguments and throw deep inside reflection — masking the real cause from callers.
     */
    fun createStruct(className: String, vararg args: Any?): Any? {
        return try {
            val clazz = Class.forName(className)
            val constructor = cachedConstructor(clazz, args.size)
            if (constructor == null) {
                val available = clazz.constructors.joinToString { "(${it.parameterCount} args)" }
                LOG.warn("No constructor on '$className' matches arity ${args.size}. Available: $available")
                return null
            }
            constructor.newInstance(*args)
        } catch (e: Exception) {
            LOG.warn("Failed to create rd struct '$className': ${e.message}")
            null
        }
    }

    /** Gets a property value from an rd struct via JavaBean getter. */
    fun getProperty(obj: Any, name: String): Any? {
        return try {
            val getter = cachedMethod(obj.javaClass, "get${name.replaceFirstChar { it.uppercaseChar() }}")
            getter.invoke(obj)
        } catch (e: Exception) {
            LOG.debug("Failed to get property '$name' from ${obj.javaClass.simpleName}: ${e.message}")
            null
        }
    }
}

const val MODEL_PKG = "com.jetbrains.rd.ide.model"

data class RiderBackendResponse<T>(
    val handled: Boolean,
    val value: T? = null
)

object RiderBackendSemanticService {
    private val LOG = logger<RiderBackendSemanticService>()

    private fun canHandleLanguage(language: String?): Boolean =
        language == null || CSHARP_LANGUAGE_IDS.any { it.equals(language, ignoreCase = true) } ||
            FSHARP_LANGUAGE_IDS.any { it.equals(language, ignoreCase = true) }

    fun isDotNetFile(file: String?): Boolean {
        val ext = file?.substringAfterLast('.', missingDelimiterValue = "")?.lowercase()
        return ext in CSHARP_EXTENSIONS || ext in FSHARP_EXTENSIONS
    }

    fun findTypes(
        project: Project,
        query: String,
        matchMode: String,
        scope: BuiltInSearchScope,
        language: String?,
        limit: Int
    ): RiderBackendResponse<List<SymbolMatch>> {
        if (!canUseBackend(project) || !canHandleLanguage(language)) return RiderBackendResponse(handled = false)
        val model = RdProtocolBridge.getModel(project) ?: return RiderBackendResponse(handled = true)
        val request = RdProtocolBridge.createStruct(
            "$MODEL_PKG.RdFindTypesRequest",
            query,
            matchMode,
            scope.wireValue,
            language,
            limit
        ) ?: return RiderBackendResponse(handled = true)
        val result = RdProtocolBridge.invokeCall(model, "findTypes", request) ?: return RiderBackendResponse(handled = true)
        @Suppress("UNCHECKED_CAST")
        val types = (RdProtocolBridge.getProperty(result, "types") as? List<Any>) ?: emptyList()
        // Backend already merges BCL/standard types into its response when scope = PROJECT_AND_LIBRARIES,
        // so no frontend-side append/merge is required. See `IndexMcpBackendHost.cs` STANDARD_DOTNET_TYPES.
        return RiderBackendResponse(
            handled = true,
            value = types.mapNotNull { rdSymbolToSymbolMatch(project, it) }
                .distinctBy { "${it.qualifiedName}:${it.file}:${it.line}" }
                .take(limit)
        )
    }

    fun findDefinition(
        project: Project,
        file: String?,
        line: Int?,
        column: Int?,
        language: String?,
        symbol: String?,
        fullElementPreview: Boolean,
        maxPreviewLines: Int
    ): RiderBackendResponse<DefinitionResult> {
        val positionTarget = file != null && line != null && column != null && isDotNetFile(file)
        val symbolTarget = language != null && symbol != null && canHandleLanguage(language)
        if (!canUseBackend(project) || (!positionTarget && !symbolTarget)) return RiderBackendResponse(handled = false)

        val target = createSemanticTarget(project, file, line, column, language, symbol)
            ?: return RiderBackendResponse(handled = true)
        val model = RdProtocolBridge.getModel(project) ?: return RiderBackendResponse(handled = true)
        val request = RdProtocolBridge.createStruct(
            "$MODEL_PKG.RdFindDefinitionRequest",
            target,
            fullElementPreview,
            maxPreviewLines
        ) ?: return RiderBackendResponse(handled = true)
        val result = RdProtocolBridge.invokeCall(model, "findDefinition", request) ?: return RiderBackendResponse(handled = true)
        val definition = RdProtocolBridge.getProperty(result, "definition") ?: return RiderBackendResponse(handled = true)
        @Suppress("UNCHECKED_CAST")
        val astPath = (RdProtocolBridge.getProperty(result, "astPath") as? List<String>) ?: emptyList()
        return RiderBackendResponse(
            handled = true,
            value = DefinitionResult(
                file = displayPath(project, RdProtocolBridge.getProperty(definition, "filePath") as? String),
                line = RdProtocolBridge.getProperty(definition, "line") as? Int ?: 1,
                column = RdProtocolBridge.getProperty(definition, "column") as? Int ?: 1,
                preview = RdProtocolBridge.getProperty(result, "preview") as? String ?: "",
                symbolName = RdProtocolBridge.getProperty(definition, "name") as? String ?: "unknown",
                astPath = astPath
            )
        )
    }

    fun findReferences(
        project: Project,
        file: String?,
        line: Int?,
        column: Int?,
        language: String?,
        symbol: String?,
        scope: BuiltInSearchScope,
        limit: Int
    ): RiderBackendResponse<List<UsageLocation>> {
        val positionTarget = file != null && line != null && column != null && isDotNetFile(file)
        val symbolTarget = language != null && symbol != null && canHandleLanguage(language)
        if (!canUseBackend(project) || (!positionTarget && !symbolTarget)) return RiderBackendResponse(handled = false)

        val target = createSemanticTarget(project, file, line, column, language, symbol)
            ?: return RiderBackendResponse(handled = true)
        val model = RdProtocolBridge.getModel(project) ?: return RiderBackendResponse(handled = true)
        val request = RdProtocolBridge.createStruct("$MODEL_PKG.RdFindReferencesRequest", target, scope.wireValue, limit)
            ?: return RiderBackendResponse(handled = true)
        val result = RdProtocolBridge.invokeCall(model, "findReferences", request) ?: return RiderBackendResponse(handled = true)
        @Suppress("UNCHECKED_CAST")
        val references = (RdProtocolBridge.getProperty(result, "references") as? List<Any>) ?: emptyList()
        return RiderBackendResponse(handled = true, value = references.map { reference ->
            UsageLocation(
                file = displayPath(project, RdProtocolBridge.getProperty(reference, "filePath") as? String),
                line = RdProtocolBridge.getProperty(reference, "line") as? Int ?: 1,
                column = RdProtocolBridge.getProperty(reference, "column") as? Int ?: 1,
                context = RdProtocolBridge.getProperty(reference, "context") as? String ?: "",
                type = RdProtocolBridge.getProperty(reference, "kind") as? String ?: "reference",
                astPath = (RdProtocolBridge.getProperty(reference, "astPath") as? List<String>) ?: emptyList()
            )
        })
    }

    fun getTypeHierarchy(
        project: Project,
        file: String,
        line: Int,
        column: Int,
        scope: BuiltInSearchScope,
        language: String
    ): RiderBackendResponse<TypeHierarchyData> {
        if (!canUseBackend(project) || !isDotNetFile(file)) return RiderBackendResponse(handled = false)
        val backendFile = resolveBackendFilePath(project, file) ?: return RiderBackendResponse(handled = true)
        val position = RdProtocolBridge.createStruct("$MODEL_PKG.RdSourcePosition", backendFile, line, column)
            ?: return RiderBackendResponse(handled = true)
        val result = invokeTypeHierarchy(project, position, scope) ?: return RiderBackendResponse(handled = true)
        return RiderBackendResponse(handled = true, value = rdTypeHierarchyToData(result, language))
    }

    /**
     * Resolve a (language, symbol) pair to a (file, line, column) position via the
     * Rider backend's symbol resolver, returning null if it couldn't be resolved or
     * if the backend is unavailable. Used by CallHierarchyTool to satisfy symbol-
     * form requests for C#/F# without going through the Java-only
     * `LanguageHandlerRegistry.getSymbolReferenceHandlerByLanguageName` path.
     */
    fun resolveSymbolToPosition(project: Project, language: String, symbol: String): Triple<String, Int, Int>? {
        if (!canUseBackend(project) || !canHandleLanguage(language)) return null
        val target = createSemanticTarget(project, null, null, null, language, symbol) ?: return null
        val model = RdProtocolBridge.getModel(project) ?: return null
        val request = RdProtocolBridge.createStruct(
            "$MODEL_PKG.RdFindDefinitionRequest",
            target,
            false,
            1
        ) ?: return null
        val result = RdProtocolBridge.invokeCall(model, "findDefinition", request) ?: return null
        val definition = RdProtocolBridge.getProperty(result, "definition") ?: return null
        val backendPath = RdProtocolBridge.getProperty(definition, "filePath") as? String ?: return null
        if (backendPath.isBlank()) return null
        val displayedPath = displayPath(project, backendPath)
        val line = RdProtocolBridge.getProperty(definition, "line") as? Int ?: return null
        val column = RdProtocolBridge.getProperty(definition, "column") as? Int ?: return null
        return Triple(displayedPath, line, column)
    }

    private fun canUseBackend(project: Project): Boolean =
        try {
            Class.forName("$MODEL_PKG.IndexMcpModel")
            Class.forName("$MODEL_PKG.IndexMcpModel_GeneratedKt")
            RdProtocolBridge.getModel(project) != null
        } catch (e: Exception) {
            LOG.debug("Rider backend semantic service unavailable: ${e.message}")
            false
        }

    private fun createSemanticTarget(
        project: Project,
        file: String?,
        line: Int?,
        column: Int?,
        language: String?,
        symbol: String?
    ): Any? {
        val backendFile = file?.let { resolveBackendFilePath(project, it) }
        return RdProtocolBridge.createStruct(
            "$MODEL_PKG.RdSemanticTarget",
            backendFile,
            line,
            column,
            language,
            symbol
        )
    }

    private fun resolveBackendFilePath(project: Project, file: String): String? {
        val direct = File(file)
        if (direct.isAbsolute && direct.exists()) return direct.canonicalPath

        val roots = listOfNotNull(project.basePath) + ProjectUtils.getModuleContentRoots(project)
        for (root in roots) {
            val candidate = File(root, file)
            if (candidate.exists()) return candidate.canonicalPath
        }
        return null
    }

    internal fun invokeTypeHierarchy(project: Project, position: Any, scope: BuiltInSearchScope): Any? {
        val model = RdProtocolBridge.getModel(project) ?: return null
        val request = RdProtocolBridge.createStruct("$MODEL_PKG.RdTypeHierarchyRequest", position, scope.wireValue)
            ?: return null
        return RdProtocolBridge.invokeCall(model, "getTypeHierarchy", request)
    }

    internal fun rdTypeHierarchyToData(result: Any, language: String): TypeHierarchyData? {
        val elementInfo = RdProtocolBridge.getProperty(result, "element") ?: return null
        @Suppress("UNCHECKED_CAST")
        val supertypes = (RdProtocolBridge.getProperty(result, "supertypes") as? List<Any>) ?: emptyList()
        @Suppress("UNCHECKED_CAST")
        val subtypes = (RdProtocolBridge.getProperty(result, "subtypes") as? List<Any>) ?: emptyList()

        return TypeHierarchyData(
            element = rdSymbolToTypeElementData(elementInfo, language),
            supertypes = supertypes.map { rdSymbolToTypeElementData(it, language) },
            subtypes = subtypes.map { rdSymbolToTypeElementData(it, language) }
        )
    }

    private fun rdSymbolToSymbolMatch(project: Project, symbol: Any): SymbolMatch? {
        val name = RdProtocolBridge.getProperty(symbol, "name") as? String ?: return null
        val filePath = RdProtocolBridge.getProperty(symbol, "filePath") as? String
        val qualifiedName = RdProtocolBridge.getProperty(symbol, "qualifiedName") as? String
        return SymbolMatch(
            name = name,
            qualifiedName = qualifiedName,
            kind = (RdProtocolBridge.getProperty(symbol, "kind") as? String ?: "UNKNOWN").lowercase(),
            file = filePath?.let { displayPath(project, it) } ?: "",
            line = RdProtocolBridge.getProperty(symbol, "line") as? Int ?: 0,
            column = RdProtocolBridge.getProperty(symbol, "column") as? Int ?: 0,
            containerName = qualifiedName?.substringBeforeLast('.', missingDelimiterValue = ""),
            language = RdProtocolBridge.getProperty(symbol, "language") as? String
        )
    }

    private fun displayPath(project: Project, filePath: String?): String {
        if (filePath.isNullOrBlank()) return ""
        val normalized = filePath.replace('\\', File.separatorChar).replace('/', File.separatorChar)
        val virtualFile = LocalFileSystem.getInstance().findFileByPath(normalized)
        if (virtualFile != null) return ProjectUtils.getToolFilePath(project, virtualFile)
        return normalized
    }
}

// ── Helper functions ────────────────────────────────────────────────────────

private val CSHARP_EXTENSIONS = setOf("cs", "csx")
private val FSHARP_EXTENSIONS = setOf("fs", "fsi", "fsx")
private val CSHARP_LANGUAGE_IDS = setOf("C#", "CSHARP", "CSharp")
private val FSHARP_LANGUAGE_IDS = setOf("F#", "FSHARP", "FSharp")

private fun riderBackendPath(file: VirtualFile): String =
    file.path.replace('/', File.separatorChar)

private fun isDotNetElement(element: PsiElement, supportedExtensions: Set<String>, supportedLanguageIds: Set<String>): Boolean {
    val langId = element.language.id
    if (supportedLanguageIds.any { it.equals(langId, ignoreCase = true) }) return true
    val ext = element.containingFile?.virtualFile?.extension?.lowercase()
    return ext in supportedExtensions
}

private fun createSourcePosition(project: Project, element: PsiElement): Any? {
    val file = element.containingFile
    val vf = file?.virtualFile
    val filePath = vf?.let { riderBackendPath(it) } ?: ""
    val document = file?.let { PsiDocumentManager.getInstance(project).getDocument(it) }
    val offset = element.textOffset
    val line = document?.getLineNumber(offset)?.plus(1) ?: 1
    val column = document?.let { offset - it.getLineStartOffset(it.getLineNumber(offset)) + 1 } ?: 1
    return RdProtocolBridge.createStruct("$MODEL_PKG.RdSourcePosition", filePath, line, column)
}

// Wrap a (file, line, column) triple in a RdSemanticTarget so that backend
// RPCs migrated to RdSemanticTarget can keep accepting position-based requests.
private fun createPositionTarget(filePath: String?, line: Int?, column: Int?): Any? =
    RdProtocolBridge.createStruct("$MODEL_PKG.RdSemanticTarget", filePath, line, column, null, null)

private fun createPositionTarget(project: Project, element: PsiElement): Any? {
    val file = element.containingFile
    val vf = file?.virtualFile
    val filePath = vf?.let { riderBackendPath(it) } ?: ""
    val document = file?.let { PsiDocumentManager.getInstance(project).getDocument(it) }
    val offset = element.textOffset
    val line = document?.getLineNumber(offset)?.plus(1) ?: 1
    val column = document?.let { offset - it.getLineStartOffset(it.getLineNumber(offset)) + 1 } ?: 1
    return createPositionTarget(filePath, line, column)
}

private fun rdSymbolToTypeElementData(symbol: Any, language: String): TypeElementData {
    return TypeElementData(
        name = RdProtocolBridge.getProperty(symbol, "name") as? String ?: "",
        qualifiedName = RdProtocolBridge.getProperty(symbol, "qualifiedName") as? String,
        file = RdProtocolBridge.getProperty(symbol, "filePath") as? String,
        line = RdProtocolBridge.getProperty(symbol, "line") as? Int,
        kind = RdProtocolBridge.getProperty(symbol, "kind") as? String ?: "UNKNOWN",
        language = language
    )
}

private fun rdSymbolToImplementationData(symbol: Any, language: String): ImplementationData? {
    return ImplementationData(
        name = RdProtocolBridge.getProperty(symbol, "name") as? String ?: "",
        file = RdProtocolBridge.getProperty(symbol, "filePath") as? String ?: return null,
        line = RdProtocolBridge.getProperty(symbol, "line") as? Int ?: return null,
        column = RdProtocolBridge.getProperty(symbol, "column") as? Int ?: 1,
        kind = (RdProtocolBridge.getProperty(symbol, "kind") as? String ?: "unknown").lowercase(),
        language = language
    )
}

private fun rdSymbolToCallElementData(symbol: Any, language: String): CallElementData? {
    return CallElementData(
        name = RdProtocolBridge.getProperty(symbol, "name") as? String ?: "",
        file = RdProtocolBridge.getProperty(symbol, "filePath") as? String ?: return null,
        line = RdProtocolBridge.getProperty(symbol, "line") as? Int ?: return null,
        column = RdProtocolBridge.getProperty(symbol, "column") as? Int ?: 1,
        language = language
    )
}

private fun rdStructureKind(kind: String): StructureKind = when (kind.uppercase()) {
    "CLASS", "ABSTRACT_CLASS" -> StructureKind.CLASS
    "INTERFACE" -> StructureKind.INTERFACE
    "STRUCT", "RECORD" -> StructureKind.RECORD
    "ENUM" -> StructureKind.ENUM
    "METHOD" -> StructureKind.METHOD
    "CONSTRUCTOR" -> StructureKind.CONSTRUCTOR
    "PROPERTY" -> StructureKind.PROPERTY
    "FIELD" -> StructureKind.FIELD
    "EVENT" -> StructureKind.PROPERTY
    "DELEGATE" -> StructureKind.CLASS
    "NAMESPACE" -> StructureKind.NAMESPACE
    else -> StructureKind.UNKNOWN
}

/**
 * Rebuilds a tree from a flat depth-annotated list of structure nodes.
 * Uses a two-pass approach since StructureNode is an immutable data class.
 */
private fun rebuildStructureTree(flatNodes: List<Any>): List<StructureNode> {
    if (flatNodes.isEmpty()) return emptyList()

    // First pass: extract flat data
    data class FlatEntry(
        val name: String,
        val kind: String,
        val modifiers: List<String>,
        val signature: String?,
        val line: Int,
        val depth: Int,
        val children: MutableList<FlatEntry> = mutableListOf()
    )

    val entries = flatNodes.map { flat ->
        @Suppress("UNCHECKED_CAST")
        FlatEntry(
            name = RdProtocolBridge.getProperty(flat, "name") as? String ?: "",
            kind = RdProtocolBridge.getProperty(flat, "kind") as? String ?: "UNKNOWN",
            modifiers = (RdProtocolBridge.getProperty(flat, "modifiers") as? List<String>) ?: emptyList(),
            signature = RdProtocolBridge.getProperty(flat, "signature") as? String,
            line = RdProtocolBridge.getProperty(flat, "line") as? Int ?: 1,
            depth = RdProtocolBridge.getProperty(flat, "depth") as? Int ?: 0
        )
    }

    // Second pass: build parent-child relationships
    val stack = mutableListOf<FlatEntry>()
    val roots = mutableListOf<FlatEntry>()

    for (entry in entries) {
        while (stack.isNotEmpty() && stack.last().depth >= entry.depth) {
            stack.removeLast()
        }
        if (stack.isEmpty()) {
            roots.add(entry)
        } else {
            stack.last().children.add(entry)
        }
        stack.add(entry)
    }

    // Third pass: convert to immutable StructureNode tree
    fun toStructureNode(entry: FlatEntry): StructureNode = StructureNode(
        name = entry.name,
        kind = rdStructureKind(entry.kind),
        modifiers = entry.modifiers,
        signature = entry.signature,
        line = entry.line,
        children = entry.children.map { toStructureNode(it) }
    )

    return roots.map { toStructureNode(it) }
}

// ── Abstract base for protocol-based handlers ───────────────────────────────

abstract class BaseRiderHandler<T>(
    final override val languageId: String,
    protected val displayLanguage: String,
    private val supportedExtensions: Set<String>,
    private val supportedLanguageIds: Set<String>,
) : LanguageHandler<T> {

    override fun isAvailable(): Boolean = RiderEnvironment.isAvailable

    override fun canHandle(element: PsiElement): Boolean =
        isAvailable() && isDotNetElement(element, supportedExtensions, supportedLanguageIds)
}

// ── Type Hierarchy Handlers ─────────────────────────────────────────────────

abstract class RiderTypeHierarchyHandler(
    languageId: String,
    displayLanguage: String,
    supportedExtensions: Set<String>,
    supportedLanguageIds: Set<String>,
) : BaseRiderHandler<TypeHierarchyData>(languageId, displayLanguage, supportedExtensions, supportedLanguageIds),
    TypeHierarchyHandler {

    override fun getTypeHierarchy(element: PsiElement, project: Project, scope: BuiltInSearchScope): TypeHierarchyData? {
        val position = createSourcePosition(project, element) ?: return null
        val result = RiderBackendSemanticService.run {
            val hierarchyResult = invokeTypeHierarchy(project, position, scope) ?: return null
            rdTypeHierarchyToData(hierarchyResult, displayLanguage)
        }
        return result
    }
}

// ── Implementations Handlers ────────────────────────────────────────────────

abstract class RiderImplementationsHandler(
    languageId: String,
    displayLanguage: String,
    supportedExtensions: Set<String>,
    supportedLanguageIds: Set<String>,
) : BaseRiderHandler<List<ImplementationData>>(languageId, displayLanguage, supportedExtensions, supportedLanguageIds),
    ImplementationsHandler {

    override fun findImplementations(element: PsiElement, project: Project, scope: BuiltInSearchScope): List<ImplementationData>? {
        val model = RdProtocolBridge.getModel(project) ?: return null
        val position = createSourcePosition(project, element) ?: return null
        val request = RdProtocolBridge.createStruct("$MODEL_PKG.RdImplementationsRequest", position, scope.wireValue) ?: return null
        val result = RdProtocolBridge.invokeCall(model, "findImplementations", request) ?: return null

        @Suppress("UNCHECKED_CAST")
        val implementations = (RdProtocolBridge.getProperty(result, "implementations") as? List<Any>) ?: emptyList()
        val directResults = implementations.mapNotNull { rdSymbolToImplementationData(it, displayLanguage) }
        if (directResults.isNotEmpty()) return directResults

        val hierarchyRequest = RdProtocolBridge.createStruct("$MODEL_PKG.RdTypeHierarchyRequest", position, scope.wireValue) ?: return directResults
        val hierarchyResult = RdProtocolBridge.invokeCall(model, "getTypeHierarchy", hierarchyRequest) ?: return directResults
        @Suppress("UNCHECKED_CAST")
        val subtypes = (RdProtocolBridge.getProperty(hierarchyResult, "subtypes") as? List<Any>) ?: emptyList()
        val subtypeResults = subtypes.mapNotNull { rdSymbolToImplementationData(it, displayLanguage) }
        return subtypeResults
    }
}

// ── Call Hierarchy Handlers ─────────────────────────────────────────────────

abstract class RiderCallHierarchyHandler(
    languageId: String,
    displayLanguage: String,
    supportedExtensions: Set<String>,
    supportedLanguageIds: Set<String>,
) : BaseRiderHandler<CallHierarchyData>(languageId, displayLanguage, supportedExtensions, supportedLanguageIds),
    CallHierarchyHandler {

    override fun getCallHierarchy(
        element: PsiElement,
        project: Project,
        direction: String,
        depth: Int,
        scope: BuiltInSearchScope
    ): CallHierarchyData? {
        val model = RdProtocolBridge.getModel(project) ?: return null
        val target = createPositionTarget(project, element) ?: return null
        val request = RdProtocolBridge.createStruct("$MODEL_PKG.RdCallHierarchyRequest", target, direction, depth, scope.wireValue)
            ?: return null
        val result = RdProtocolBridge.invokeCall(model, "getCallHierarchy", request) ?: return null

        val root = RdProtocolBridge.getProperty(result, "root") ?: return null
        @Suppress("UNCHECKED_CAST")
        val calls = (RdProtocolBridge.getProperty(result, "calls") as? List<Any>) ?: emptyList()
        // Single seen set shared across the whole tree so that sibling subtrees do not
        // re-expand callees they have collectively already visited. Without this dedup,
        // wide call graphs trigger exponential backend round-trips (root cause of the
        // historical "deep call hierarchy is slow" symptom).
        val seen = mutableSetOf<String>()
        val convertedCalls = calls.mapNotNull { rdSymbolToCallElementData(it, displayLanguage) }
            .filter { seen.add(callKey(it)) }
            .take(MAX_CHILDREN_PER_LEVEL)
            .map { call ->
                expandCallHierarchy(project, call, direction, depth - 1, scope, seen)
            }

        return CallHierarchyData(
            element = rdSymbolToCallElementData(root, displayLanguage) ?: return null,
            calls = convertedCalls
        )
    }

    private fun expandCallHierarchy(
        project: Project,
        call: CallElementData,
        direction: String,
        remainingDepth: Int,
        scope: BuiltInSearchScope,
        seen: MutableSet<String>
    ): CallElementData {
        if (remainingDepth <= 0) return call.copy(children = emptyList())
        val target = createPositionTarget(call.file, call.line, call.column)
            ?: return call.copy(children = emptyList())
        val request = RdProtocolBridge.createStruct("$MODEL_PKG.RdCallHierarchyRequest", target, direction, remainingDepth, scope.wireValue)
            ?: return call.copy(children = emptyList())
        val model = RdProtocolBridge.getModel(project) ?: return call.copy(children = emptyList())
        val result = RdProtocolBridge.invokeCall(model, "getCallHierarchy", request) ?: return call.copy(children = emptyList())
        @Suppress("UNCHECKED_CAST")
        val children = (RdProtocolBridge.getProperty(result, "calls") as? List<Any>) ?: emptyList()
        val convertedChildren = children.mapNotNull { rdSymbolToCallElementData(it, displayLanguage) }
            .filter { seen.add(callKey(it)) }
            .take(MAX_CHILDREN_PER_LEVEL)
            .map { child -> expandCallHierarchy(project, child, direction, remainingDepth - 1, scope, seen) }
        return call.copy(children = convertedChildren)
    }

    private fun callKey(call: CallElementData): String =
        "${call.file}:${call.line}:${call.column}:${call.name}"

    private companion object {
        // Mirrors JavaCallHierarchyHandler.MAX_RESULTS_PER_LEVEL to keep behaviour consistent
        // across IDEs and to bound RD round-trips for fan-out methods.
        const val MAX_CHILDREN_PER_LEVEL = 20
    }
}

// ── Super Methods Handlers ──────────────────────────────────────────────────

abstract class RiderSuperMethodsHandler(
    languageId: String,
    displayLanguage: String,
    supportedExtensions: Set<String>,
    supportedLanguageIds: Set<String>,
) : BaseRiderHandler<SuperMethodsData>(languageId, displayLanguage, supportedExtensions, supportedLanguageIds),
    SuperMethodsHandler {

    override fun findSuperMethods(element: PsiElement, project: Project): SuperMethodsData? {
        val model = RdProtocolBridge.getModel(project) ?: return null
        val position = createSourcePosition(project, element) ?: return null
        val request = RdProtocolBridge.createStruct("$MODEL_PKG.RdSuperMethodsRequest", position) ?: return null
        val result = RdProtocolBridge.invokeCall(model, "findSuperMethods", request) ?: return null

        val method = RdProtocolBridge.getProperty(result, "method") ?: return null
        @Suppress("UNCHECKED_CAST")
        val hierarchy = (RdProtocolBridge.getProperty(result, "hierarchy") as? List<Any>) ?: emptyList()

        fun usableName(value: String?): String =
            value?.takeUnless { it.isBlank() } ?: "unknown"
        val methodName = usableName(RdProtocolBridge.getProperty(method, "name") as? String)

        return SuperMethodsData(
            method = MethodData(
                name = methodName,
                signature = (RdProtocolBridge.getProperty(method, "signature") as? String)
                    ?.takeUnless { it.isBlank() || it.equals("unknown", ignoreCase = true) } ?: methodName,
                containingClass = (RdProtocolBridge.getProperty(method, "qualifiedName") as? String)
                    ?.substringBeforeLast('.', "unknown") ?: "unknown",
                file = RdProtocolBridge.getProperty(method, "filePath") as? String ?: return null,
                line = RdProtocolBridge.getProperty(method, "line") as? Int ?: return null,
                column = RdProtocolBridge.getProperty(method, "column") as? Int ?: 1,
                language = displayLanguage
            ),
            hierarchy = hierarchy.map { superInfo ->
                val symbol = RdProtocolBridge.getProperty(superInfo, "symbol")
                val superName = usableName(symbol?.let { RdProtocolBridge.getProperty(it, "name") as? String })
                SuperMethodData(
                    name = superName,
                    signature = (symbol?.let { RdProtocolBridge.getProperty(it, "signature") as? String })
                        ?.takeUnless { it.isBlank() || it.equals("unknown", ignoreCase = true) } ?: superName,
                    containingClass = RdProtocolBridge.getProperty(superInfo, "containingTypeName") as? String ?: "",
                    containingClassKind = RdProtocolBridge.getProperty(superInfo, "containingTypeKind") as? String ?: "CLASS",
                    file = symbol?.let { RdProtocolBridge.getProperty(it, "filePath") as? String },
                    line = symbol?.let { RdProtocolBridge.getProperty(it, "line") as? Int },
                    column = symbol?.let { RdProtocolBridge.getProperty(it, "column") as? Int },
                    isInterface = RdProtocolBridge.getProperty(superInfo, "isInterface") as? Boolean ?: false,
                    depth = RdProtocolBridge.getProperty(superInfo, "depth") as? Int ?: 0,
                    language = displayLanguage
                )
            }
        )
    }
}

// ── Structure Handlers ──────────────────────────────────────────────────────

abstract class RiderStructureHandler(
    languageId: String,
    displayLanguage: String,
    supportedExtensions: Set<String>,
    supportedLanguageIds: Set<String>,
) : BaseRiderHandler<List<StructureNode>>(languageId, displayLanguage, supportedExtensions, supportedLanguageIds),
    StructureHandler {

    override fun getFileStructure(file: PsiFile, project: Project): List<StructureNode> {
        val model = RdProtocolBridge.getModel(project) ?: return emptyList()
        val filePath = file.virtualFile?.let { riderBackendPath(it) } ?: return emptyList()
        val request = RdProtocolBridge.createStruct("$MODEL_PKG.RdFileStructureRequest", filePath) ?: return emptyList()
        val result = RdProtocolBridge.invokeCall(model, "getFileStructure", request) ?: return emptyList()

        @Suppress("UNCHECKED_CAST")
        val nodes = (RdProtocolBridge.getProperty(result, "nodes") as? List<Any>) ?: emptyList()
        return rebuildStructureTree(nodes)
    }
}

// ── Concrete C# Handlers ────────────────────────────────────────────────────

class RiderCSharpTypeHierarchyHandler : RiderTypeHierarchyHandler("C#", "C#", CSHARP_EXTENSIONS, CSHARP_LANGUAGE_IDS)
class RiderCSharpImplementationsHandler : RiderImplementationsHandler("C#", "C#", CSHARP_EXTENSIONS, CSHARP_LANGUAGE_IDS)
class RiderCSharpCallHierarchyHandler : RiderCallHierarchyHandler("C#", "C#", CSHARP_EXTENSIONS, CSHARP_LANGUAGE_IDS)
class RiderCSharpSuperMethodsHandler : RiderSuperMethodsHandler("C#", "C#", CSHARP_EXTENSIONS, CSHARP_LANGUAGE_IDS)
class RiderCSharpStructureHandler : RiderStructureHandler("C#", "C#", CSHARP_EXTENSIONS, CSHARP_LANGUAGE_IDS)

// ── Concrete F# Handlers ────────────────────────────────────────────────────

class RiderFSharpTypeHierarchyHandler : RiderTypeHierarchyHandler("F#", "F#", FSHARP_EXTENSIONS, FSHARP_LANGUAGE_IDS)
class RiderFSharpImplementationsHandler : RiderImplementationsHandler("F#", "F#", FSHARP_EXTENSIONS, FSHARP_LANGUAGE_IDS)
class RiderFSharpCallHierarchyHandler : RiderCallHierarchyHandler("F#", "F#", FSHARP_EXTENSIONS, FSHARP_LANGUAGE_IDS)
class RiderFSharpSuperMethodsHandler : RiderSuperMethodsHandler("F#", "F#", FSHARP_EXTENSIONS, FSHARP_LANGUAGE_IDS)
class RiderFSharpStructureHandler : RiderStructureHandler("F#", "F#", FSHARP_EXTENSIONS, FSHARP_LANGUAGE_IDS)
